// src/providers/DashboardPreferencesProvider.tsx
// Proveedor de preferencias personales (Tema e Idioma) exclusivo para el dashboard de cada colaborador.
// Soporta Español, Inglés y Chino Simplificado con diccionarios completos.

'use client';

import React, { createContext, useContext, useState, useEffect, useCallback, ReactNode } from 'react';
import { useAuth } from './AuthProvider';

export type DashboardTheme = 'obsidian' | 'midnight' | 'emerald' | 'purple' | 'titanium' | 'light';
export type DashboardLanguage = 'es' | 'en' | 'zh';

export interface ThemeConfig {
  id: DashboardTheme;
  name: string;
  nameEn: string;
  nameZh: string;
  previewBg: string;
  previewAccent: string;
  cardBg: string;
  borderAccent: string;
  accentColor: string;
  description: string;
  descriptionEn: string;
  descriptionZh: string;
}

export const DASHBOARD_THEMES: Record<DashboardTheme, ThemeConfig> = {
  obsidian: {
    id: 'obsidian',
    name: 'Obsidian Negro (Apple)',
    nameEn: 'Obsidian Black (Apple)',
    nameZh: '黑曜石纯黑 (Apple黑)',
    previewBg: '#000000',
    previewAccent: '#2997ff',
    cardBg: '#0d0d10',
    borderAccent: 'rgba(255, 255, 255, 0.08)',
    accentColor: '#2997ff',
    description: 'Negro puro OLED de contraste ultra alto con acentos sutiles.',
    descriptionEn: 'Pure OLED black with high contrast and subtle accents.',
    descriptionZh: '极致OLED纯黑高对比度背景，搭配细腻微光边框。',
  },
  light: {
    id: 'light',
    name: 'Apple Claro (Blanco Puro)',
    nameEn: 'Apple Light (Pure White)',
    nameZh: '苹果纯白 (明亮白)',
    previewBg: '#f5f5f7',
    previewAccent: '#0071e3',
    cardBg: '#ffffff',
    borderAccent: 'rgba(0, 0, 0, 0.08)',
    accentColor: '#0071e3',
    description: 'Diseño claro y limpio estilo macOS con máxima legibilidad y confort diurno.',
    descriptionEn: 'Clean light macOS design with maximum day-time readability and comfort.',
    descriptionZh: '清爽明亮 macOS 纯白风格，高对比清晰易读。',
  },
  midnight: {
    id: 'midnight',
    name: 'Midnight Navy (Azul)',
    nameEn: 'Midnight Navy (Blue)',
    nameZh: '午夜深蓝 (科技蓝)',
    previewBg: '#050c18',
    previewAccent: '#38bdf8',
    cardBg: '#081426',
    borderAccent: 'rgba(56, 189, 248, 0.18)',
    accentColor: '#38bdf8',
    description: 'Azul noche espacial con acentos zafiro y tonos neón.',
    descriptionEn: 'Deep cosmic navy with sapphire accents and neon hints.',
    descriptionZh: '深邃宇宙深蓝配蓝宝石荧光，现代科技质感。',
  },
  emerald: {
    id: 'emerald',
    name: 'Emerald Forest (Verde)',
    nameEn: 'Emerald Forest (Green)',
    nameZh: '翡翠墨绿 (自然绿)',
    previewBg: '#041108',
    previewAccent: '#30d158',
    cardBg: '#081c10',
    borderAccent: 'rgba(48, 209, 88, 0.2)',
    accentColor: '#30d158',
    description: 'Verde esmeralda refinado para máxima claridad y confort visual.',
    descriptionEn: 'Refined emerald green for maximum visual clarity and comfort.',
    descriptionZh: '典雅翡翠翠绿，护眼舒适，信息呈现清晰分明。',
  },
  purple: {
    id: 'purple',
    name: 'Purple Royal (Púrpura)',
    nameEn: 'Purple Royal (Purple)',
    nameZh: '皇家魅紫 (高贵紫)',
    previewBg: '#0f051a',
    previewAccent: '#bf5af2',
    cardBg: '#180a29',
    borderAccent: 'rgba(191, 90, 242, 0.22)',
    accentColor: '#bf5af2',
    description: 'Púrpura amatista lujoso con reflejos violeta de noche.',
    descriptionEn: 'Luxurious amethyst purple with midnight violet highlights.',
    descriptionZh: '奢华紫晶渐变与夜色紫晕，尊享尊荣视觉体验。',
  },
  titanium: {
    id: 'titanium',
    name: 'Titanium Graphite (Gris)',
    nameEn: 'Titanium Graphite (Gray)',
    nameZh: '钛金原色 (Mac灰)',
    previewBg: '#121216',
    previewAccent: '#ffd60a',
    cardBg: '#1c1c22',
    borderAccent: 'rgba(255, 255, 255, 0.14)',
    accentColor: '#ffd60a',
    description: 'Gris titanio pulido estilo MacBook Pro con acento ámbar.',
    descriptionEn: 'Polished titanium gray MacBook Pro style with amber touch.',
    descriptionZh: 'MacBook Pro 精致哑光钛金属质感，琥珀金微光点缀。',
  },
};

export const TRANSLATIONS: Record<DashboardLanguage, Record<string, string>> = {
  es: {
    // Navegación
    nav_dashboard_programmer: 'Centro de Comando',
    nav_dashboard_owner: 'Panel Ejecutivo',
    nav_dashboard_employee: 'Mi Estación',
    nav_chat_team: 'Chat del Equipo',
    nav_chat_staff: 'Chat del Personal',
    nav_products: 'Gestión de Productos',
    nav_categories: 'Categorías',
    nav_owners: 'Dueños de Tienda',
    nav_employees: 'Gestión de Empleados',
    nav_delivery: 'Empresas de Delivery',
    nav_catalog: 'Catálogo de Tienda',
    nav_settings: 'Ajustes de mi Panel',

    // Ajustes
    settings_title: 'Ajustes del Dashboard',
    settings_subtitle: 'Personaliza el tema visual y el idioma exclusivamente para tu sesión.',
    settings_notice: 'Estas configuraciones se aplican solo a tu cuenta y no modifican el diseño de la tienda pública ni el panel de tus compañeros.',
    settings_theme_label: 'Tema Visual del Panel',
    settings_lang_label: 'Idioma de tu Dashboard',
    settings_lang_es: 'Español (Latinoamérica)',
    settings_lang_en: 'English (United States)',
    settings_lang_zh: '中文 (简体中文)',
    settings_applied: '¡Preferencias actualizadas con éxito!',

    // Acciones y estados comunes
    btn_save: 'Guardar Ajustes',
    btn_close: 'Cerrar',
    btn_open_chat: 'Abrir Mensajería',
    btn_copy_link: 'Copiar Enlace',
    btn_pause_shift: 'Pausar Turno',
    btn_resume_shift: 'Reanudar Turno',
    status_on_duty: 'En Servicio',
    status_paused: 'En Pausa',
    status_connected: 'En Línea',
    search_placeholder: 'Buscar...',
    logout: 'Cerrar Sesión',
    verify_phone: 'Verificar Celular',
    change_branch: 'Cambiar de Sucursal',
    no_branches: 'Sin sucursales',

    // Dock Móvil y Badges
    tab_summary: 'Resumen',
    tab_products: 'Productos',
    tab_chat: 'Chat',
    tab_owners: 'Dueños',
    tab_delivery: 'Delivery',
    tab_menu: 'Menú',
    tab_station: 'Mi Estación',
    tab_store: 'Tienda',
    tab_employees: 'Empleados',
    back_to_store: 'Volver a la Tienda',
    view_public_store: 'Ver Tienda Pública',
    collapse_sidebar: 'Colapsar barra lateral',
    expand_sidebar: 'Expandir barra lateral',
    superadmin: 'Superadmin',
    role_owner: 'Dueño',
    role_employee: 'Empleado',
    role_programmer: 'Programador',
    badge_live: 'En Vivo',
    badge_inventory: 'Inventario',
    badge_catalog: 'Catálogo',
    badge_management: 'Gestión',
    badge_shipping: 'Envíos',

    // Empleado Dashboard
    dash_active_station: 'Estación Activa',
    dash_branch_main: 'Sucursal Principal',
    dash_welcome: 'Bienvenido',
    dash_employee_subtitle: 'Panel operativo adaptado a tus funciones de',
    dash_shift_status: 'Estado del Turno',
    dash_on_duty_label: 'En Servicio',
    dash_on_pause_label: 'En Pausa',
    dash_tab_orders_qr: 'Pedidos y Validación QR',
    dash_tab_station_tools: 'Herramientas de Estación',
    dash_tab_referral: 'Mi Enlace de Referido',
    dash_collaborative_title: 'Subir y Administrar Productos de la Tienda',
    dash_collaborative_desc: 'Colabora agregando nuevos productos, precios, descripciones y categorías. Puedes proponer descuentos para autorización del Dueño o Programador.',
    dash_manage_products_btn: 'Gestionar Productos',
    dash_internal_chat_title: 'Chat Interno del Personal',
    dash_internal_chat_desc: 'Comunícate al instante con tus compañeros de turno, coordina relevos de caja, reporta alertas urgentes o consulta disponibilidad de stock.',
    dash_open_chat_btn: 'Abrir Mensajería',
    dash_cashier_opening: 'Apertura de Caja',
    dash_cashier_opening_note: 'Fondo inicial confirmado',
    dash_cashier_sales_today: 'Cobros Realizados (Hoy)',
    dash_cashier_sales_waiting: 'Esperando primeras transacciones',
    dash_cashier_tickets: 'Tickets Emitidos',
    dash_cashier_tickets_note: 'Turno actual',
    dash_warehouse_received: 'Artículos Ingresados',
    dash_warehouse_received_note: 'Últimos 7 días',
    dash_warehouse_low_stock: 'Alertas de Stock Bajo',
    dash_warehouse_low_stock_note: 'Revisión recomendada',
    dash_warehouse_transfers: 'Movimientos de Sucursal',
    dash_warehouse_transfers_note: 'Traslados pendientes',
    dash_general_active_tasks: 'Tareas Activas',
    dash_general_tasks_assigned: 'Asignadas hoy',
    dash_general_urgent_alerts: 'Avisos Urgentes',
    dash_general_all_clear: 'Sin pendientes críticos',
    dash_general_branch: 'Sucursal Operativa',

    // QR Generator Panel
    qr_panel_title: 'Código QR para Repartidores',
    qr_panel_desc: 'El repartidor escanea este código al llegar a {branch} para validar el pedido y registrar el pago.',
    qr_type_dynamic: 'Dinámico (2 min)',
    qr_type_fixed: 'Fijo (Mostrador)',
    qr_security_flow: 'Flujo de Seguridad',
    qr_step_1: 'El repartidor llega al mostrador y escanea este QR con su cámara.',
    qr_step_2: 'Ingresa su nombre y selecciona su empresa de delivery (sin contraseña).',
    qr_step_3: 'Selecciona al cliente de la lista de pedidos pendientes.',
    qr_step_4: 'Revisa la mercadería y registra el pago para completar la venta.',
    qr_direct_link: 'Enlace directo de validación',
    qr_btn_regenerate: 'Regenerar Código QR Ahora',
    qr_auto_refresh: 'Se actualiza automáticamente en',
    qr_generating: 'Generando QR...',
    qr_copied: '¡Enlace copiado!',

    // Orders Panel
    orders_title: 'Monitor de Pedidos',
    orders_inbox: 'Bandeja de Mensajes',
    orders_live: 'Firestore en vivo',
    orders_tab_all: 'Todos',
    orders_tab_pending: 'Pendientes',
    orders_tab_preparing: 'En Preparación',
    orders_tab_waiting: 'En Espera',
    orders_tab_ready: 'Listos QR',
    orders_tab_validated: 'Validados',
    orders_empty_title: 'No hay pedidos en esta categoría',
    orders_empty_desc: 'Los nuevos pedidos aparecerán automáticamente aquí.',
    orders_card_order: 'Pedido',
    orders_card_customer: 'Cliente',
    orders_card_total: 'Total',
    orders_card_items: 'ítems',
    orders_btn_prepare: 'Preparar Pedido',
    orders_btn_missing: 'Falta Producto',
    orders_btn_ready: 'Listo para Entrega',
    orders_btn_chat: 'Chat con Cliente',

    // Dueño Dashboard
    owner_portal_badge: 'Portal Ejecutivo del Dueño',
    owner_active_branches: 'Sucursales Activas',
    owner_dashboard_title: 'Panel de Control de Tienda',
    owner_dashboard_desc: 'Gestiona las sucursales, supervisa a tu personal y monitorea los pedidos en tiempo real.',
    owner_btn_new_branch: 'Nueva Sucursal',
    owner_btn_products: 'Productos y Descuentos',
    owner_btn_employees: 'Gestionar Empleados',
    owner_tab_orders: 'Pedidos y Delivery',
    owner_tab_qr: 'Códigos QR de Sucursal',
    owner_tab_branches: 'Sucursales',
    owner_tab_metrics: 'Métricas y Ventas',
    owner_stat_sales_today: 'Ventas de Hoy',
    owner_stat_pending_orders: 'Pedidos Pendientes',
    owner_stat_active_products: 'Productos Activos',
    owner_stat_active_staff: 'Personal de Turno',

    // Programador Dashboard
    prog_console_badge: 'Consola Principal del Desarrollador',
    prog_superadmin: 'SUPERADMIN ACCESS',
    prog_title: 'Panel de Control Maestro',
    prog_desc: 'Monitoreo integral de Firebase Auth, gestión de programadores, roles privilegiados, invitaciones de dueños y registro de empleados.',
    prog_btn_add_prog: '+ Programadores',
    prog_btn_delivery: 'Delivery',
    prog_btn_owners: 'Dueños',
    prog_tab_overview: 'Resumen General',
    prog_tab_programmers: 'Equipo de Programadores',
    prog_tab_owners: 'Jefes & Dueños',
    prog_tab_delivery: 'Empresas de Delivery',
    prog_tab_employees: 'Registro de Empleados',
    prog_tab_audit: 'Auditoría de Acciones',
    prog_tab_database: 'Base de Datos RTDB',

    // Áreas de trabajo
    area_caja: 'Caja',
    area_bodega: 'Bodega',
    area_empaque: 'Empaque',
    area_cocina: 'Cocina',
    area_despacho: 'Despacho',
    area_general: 'General',

    // Referral
    ref_title: 'Mi Enlace de Referido',
    ref_desc: 'Comparte tu enlace o código QR para recibir crédito por cada venta realizada.',

    // Productos e Inventario
    prod_module_badge: 'Módulo de Inventario Unificado',
    prod_management_title: 'Gestión de Productos y Descuentos',
    prod_management_desc: 'Dueño y empleados pueden subir productos con sus precios, descripciones y categorías. Los descuentos propuestos por empleados requieren autorización del Dueño o Programador antes de mostrarse en la tienda pública.',
    prod_btn_new_category: 'Nueva Categoría',
    prod_btn_add_product: 'Agregar Producto',
    prod_pending_discounts_title: 'Solicitudes de Descuento Pendientes de Autorización',
    prod_can_authorize: 'Tienes permisos para aprobar o rechazar estas rebajas',
    prod_waiting_review: 'En espera de revisión por el Dueño o Programador',
    prod_discount_reason: 'Motivo',
    prod_proposed_by: 'Propuesto por',
    prod_btn_approve: 'Aprobar Descuento',
    prod_btn_reject: 'Rechazar',
    prod_pending_badge: 'Pendiente de autorización',
    prod_search_placeholder: 'Buscar por nombre, categoría o descripción...',
    prod_filter_all_cats: 'Todas las categorías',
    prod_filter_all_status: 'Todos los estados',
    prod_filter_discounted: 'Con descuento activo',
    prod_filter_pending: 'Descuentos pendientes',
    prod_empty_title: 'No hay productos en esta vista',
    prod_empty_desc: 'Puedes agregar nuevos productos con precios, descripciones y categorías usando el botón superior.',
    prod_btn_add_first: 'Agregar Primer Producto',
    prod_card_edit: 'Editar',
    prod_card_discount: 'Descuento',
    prod_card_barcode: 'Código de Barras',
    prod_card_in_stock: 'En stock',
    prod_card_low_stock: 'Bajo stock',
    prod_card_out_of_stock: 'Agotado',
    prod_cat_tools: 'Herramientas & Ferretería',
    prod_cat_shoes: 'Calzado & Zapatos',
    prod_cat_clothing: 'Ropa & Moda',
    prod_cat_lingerie: 'Ropa Íntima & Fajas',
    prod_cat_cosmetics: 'Cosméticos & Belleza',
    prod_cat_electronics: 'Electrónica & Gadgets',
    prod_cat_snacks: 'Bocadillos Chinos & Snacks',
    prod_cat_caps: 'Gorras & Accesorios',
    prod_cat_home: 'Hogar & Cocina',
    prod_cat_seasonal: 'Productos de Temporada',
    prod_cat_adult: 'Juguetes Sexuales',
    prod_cat_general: 'General',

    // Chat
    chat_title: 'Chat Interno del Personal',
    chat_desc: 'Comunícate en tiempo real con tus compañeros de sucursal, consulta stock y coordina turnos.',
    chat_search_placeholder: 'Buscar canal o compañero...',
    chat_team_rooms: 'Salas de Equipo',
    chat_coworkers: 'Compañeros de Turno',
    chat_no_coworkers: 'No se encontraron compañeros.',
    chat_on_shift: 'En turno',
    chat_active_channel: 'Canal Activo',
    chat_syncing: 'Sincronizando mensajes del canal...',
    chat_empty_title: 'No hay mensajes aún en este canal',
    chat_empty_desc: '¡Sé el primero en escribir! Puedes consultar stock, coordinar turnos o avisar a tus compañeros.',
    chat_urgent_badge: 'AVISO URGENTE',
    chat_shift_badge: 'RELEVO DE TURNO',
    chat_stock_badge: 'CONSULTA DE STOCK',
    chat_quick_tags: 'Avisos Rápidos:',
    chat_tag_urgent: 'Urgente',
    chat_tag_shift: 'Turno',
    chat_tag_stock: 'Stock',
    chat_placeholder_urgent: 'Escribe un aviso prioritario o urgente...',
    chat_placeholder_shift: 'Reporta inicio, cambio o pausa de turno...',
    chat_placeholder_stock: 'Pregunta o avisa sobre stock de un producto...',
    chat_placeholder_general: 'Mensaje para',
    chat_btn_send: 'Enviar',
    chat_ch_general: 'Sala General del Equipo',
    chat_ch_general_desc: 'Comunicados de toda la tienda',
    chat_ch_ferreteria: 'Ferretería & Mostrador',
    chat_ch_ferreteria_desc: 'Consultas de herramientas, precios, especificaciones y stock',
    chat_ch_caja: 'Caja & Facturación',
    chat_ch_caja_desc: 'Arqueos, comprobantes de pago, tickets y confirmación de ventas',
    chat_ch_bodega: 'Bodega & Despacho',
    chat_ch_bodega_desc: 'Control de existencias, recepción de paquetes y pedidos listos',

    // Dueño adicional
    owner_onboarding_required: 'Configuración Inicial Requerida',
    owner_onboarding_welcome: 'Bienvenido a Sayta Mall',
    owner_onboarding_desc: 'Para comenzar a recibir pedidos y dar de alta a tus empleados, crea tu primera sucursal operativa.',
    owner_stat_active_branch: 'Sucursal Activa',
    owner_stat_online: 'En línea',
    owner_stat_currency: 'Moneda de Operación',
    owner_stat_currency_local: 'Estándar local',
    owner_stat_dispatch: 'Despacho',
    owner_stat_enabled: 'Habilitado',
    owner_stat_staff: 'Personal',
    owner_stat_active: 'Activo',
    owner_stat_manager_avail: 'Gestor disponible',
    owner_card_employees_title: 'Gestión de Empleados & Turnos',
    owner_card_employees_desc: 'Agrega los correos y contraseñas de tus colaboradores, asígnales su sucursal y su área correspondiente (Caja, Bodega, Ventas, Limpieza, Atención o General).',
    owner_card_employees_btn: 'Abrir Gestor de Personal y Áreas',
    owner_card_products_title: 'Catálogo y Descuentos',
    owner_card_products_desc: 'Supervisa los productos subidos por tus colaboradores y aprueba promociones o descuentos sugeridos para tu sucursal.',
    owner_card_products_btn: 'Gestionar Productos',
    owner_registered_branches: 'registradas',
    owner_referral_program: 'Mi Programa de Referidos',
    owner_single_branch_active: 'Sucursal Activa',
    owner_multi_branch_active: 'Sucursales Activas',

    // Programador adicional
    prog_tab_staff: 'Trabajadores & Empleados',
    prog_tab_system: 'Estado del Sistema',
    prog_tab_logs: 'Logs de Auditoría',
    prog_tab_audit_staff: 'Auditoría Empleados',
    prog_tab_users: 'Usuarios Registrados',
    prog_tab_referral: 'Mi Enlace Referido',
    prog_tab_cronjobs: 'Cron Jobs',
    prog_tab_qr_branch: 'Códigos QR Sucursal',

    // Reportar Faltante Modal
    missing_modal_title: 'Reportar Producto No Disponible',
    missing_modal_desc: 'Al marcar productos no disponibles, el pedido pasará a En espera del cliente y se bloqueará para el delivery. Se creará un chat en vivo con opciones de decisión.',
    missing_btn_notify: 'Pausar y Notificar al Cliente',
    missing_btn_add_another: 'Agregar otro producto faltante',
    missing_opt_out_of_stock: 'Agotado en sucursal',
    missing_opt_damaged: 'Unidad dañada o vencida',
    missing_opt_inventory_diff: 'Diferencia de inventario',
    missing_suggest_title: 'Sugerir alternativa (Opcional)',
    missing_substitute_name: 'Nombre del producto sustituto',
    missing_substitute_price: 'Precio sugerido',

    // Delivery Page
    delivery_badge: 'Logística & Distribución',
    delivery_live_badge: 'EN VIVO',
    delivery_title: 'Empresas de Delivery / Envíos',
    delivery_desc: 'Registra y gestiona las empresas de repartos locales. Los clientes podrán seleccionarlas en el checkout y enviarles los pedidos directamente a su WhatsApp o canalizarlos por la web.',
    delivery_btn_register: 'Registrar Empresa',
    delivery_stat_total: 'Total Empresas',
    delivery_stat_total_sub: 'Registradas en el sistema',
    delivery_stat_active: 'Activas en Checkout',
    delivery_stat_active_sub: 'Disponibles para clientes',
    delivery_stat_zones: 'Zonas Cubiertas',
    delivery_stat_zones_sub: 'Áreas de reparto activas',
    delivery_stat_orders: 'Pedidos Canalizados',
    delivery_stat_orders_sub: 'Vía Web y WhatsApp',
    delivery_search_placeholder: 'Buscar por nombre, WhatsApp o zona...',
    delivery_filter_all: 'Todas',
    delivery_filter_active: 'Activas',
    delivery_filter_inactive: 'Inactivas',
    delivery_loading: 'Cargando empresas de delivery...',
    delivery_empty_title: 'No se encontraron empresas de delivery',
    delivery_empty_search: 'Ninguna empresa coincide con la búsqueda. Intenta con otro término.',
    delivery_empty_first: 'Registra tu primera empresa de delivery para que los clientes puedan elegirla al pagar.',
    delivery_btn_register_now: 'Registrar Empresa Ahora',
    delivery_active_label: 'Activa en Checkout',
    delivery_inactive_label: 'Inactiva (Oculta)',
    delivery_rate_label: 'Tarifa de Envío',
    delivery_rate_value: 'Según Destino',
    delivery_zones_label: 'Zonas de cobertura',
    delivery_orders_label: 'Pedidos',
    delivery_btn_test: 'Probar WhatsApp',
    delivery_btn_edit: 'Editar',
    delivery_btn_toggle_active: 'Activar empresa',
    delivery_btn_toggle_inactive: 'Desactivar empresa',
    delivery_btn_delete: 'Eliminar empresa',
    delivery_modal_create_title: 'Registrar Nueva Empresa de Delivery',
    delivery_modal_edit_title: 'Editar Empresa de Delivery',
    delivery_form_name: 'Nombre de la empresa *',
    delivery_form_name_placeholder: 'Ej. Moto Express Chichigalpa',
    delivery_form_whatsapp: 'WhatsApp Internacional *',
    delivery_form_phone: 'Teléfono convencional (opcional)',
    delivery_form_email: 'Correo electrónico (opcional)',
    delivery_form_zones: 'Zonas de cobertura (separadas por coma) *',
    delivery_form_zones_placeholder: 'Ej. Centro, Reparto San Antonio, Barrio El Carmen',
    delivery_form_logo: 'URL del logo (opcional)',
    delivery_form_status: 'Estado: Activa en Checkout',
    delivery_btn_cancel: 'Cancelar',
    delivery_btn_save: 'Guardar Cambios',
    delivery_btn_create: 'Registrar Empresa',
    delivery_btn_submitting: 'Guardando...',
    delivery_delete_title: 'Eliminar Empresa de Delivery',
    delivery_delete_desc: '¿Estás seguro de que deseas eliminar',
    delivery_delete_warning: 'Esta acción puede desactivarla si tiene pedidos asociados.',
    delivery_btn_delete_confirm: 'Sí, eliminar empresa',
    delivery_btn_deleting: 'Eliminando...',

    // Owners Management Page
    owners_badge: 'Consola Superadmin',
    owners_count_label: 'Dueños Registrados',
    owners_title: 'Gestión de Dueños de Tienda',
    owners_desc: 'Administra los accesos de franquiciatarios y dueños de tienda. Invítalos mediante correo, suspende accesos temporalmente, utiliza el modo soporte para asistirlos o elimina registros con confirmación en dos pasos.',
    owners_btn_add: 'Agregar Dueño',
    owners_search_placeholder: 'Buscar por nombre, correo o nombre de tienda...',
    owners_col_owner: 'Dueño & Correo',
    owners_col_store: 'Tienda Asignada',
    owners_col_branches: 'Sucursales',
    owners_col_status: 'Estado',
    owners_col_date: 'Fecha de Alta',
    owners_col_actions: 'Acciones',
    owners_status_active: 'Activo',
    owners_status_suspended: 'Suspendido',
    owners_status_pending: '7d Pendiente',
    owners_invite_pending: 'Invitación pendiente',
    owners_branches_label: 'sucursal',
    owners_branches_plural: 'sucursales',
    owners_btn_view: 'Ver panel del dueño',
    owners_btn_support: 'Modo soporte',
    owners_btn_suspend: 'Suspender acceso',
    owners_btn_restore: 'Restaurar acceso',
    owners_btn_delete: 'Eliminar dueño',
    owners_empty_title: 'Ningún dueño registrado aún',
    owners_empty_desc: 'Agrega el primer dueño de franquicia con su correo y contraseña para comenzar.',
    owners_modal_title: 'Registrar Nuevo Dueño de Tienda',
    owners_modal_desc: 'Crea las credenciales de acceso del dueño. Se le enviará un correo automático de bienvenida con instrucciones de inicio de sesión.',
    owners_form_name: 'Nombre del dueño *',
    owners_form_name_ph: 'Ej. Xia Xue',
    owners_form_email: 'Correo electrónico *',
    owners_form_email_ph: 'dueno@ejemplo.com',
    owners_form_store: 'Nombre de la tienda *',
    owners_form_store_ph: 'Ej. Sayta Mall Chichigalpa',
    owners_form_password: 'Contraseña temporal *',
    owners_form_password_ph: 'Mínimo 6 caracteres',
    owners_form_branch: 'Asignar Sucursal(es)',
    owners_btn_create: 'Registrar Dueño',
    owners_btn_creating: 'Registrando...',
    owners_delete_title: 'Eliminar Dueño de Tienda',
    owners_delete_desc: 'Esta acción es irreversible. Escribe el nombre exacto de la tienda para confirmar:',
    owners_delete_type_label: 'Escribe el nombre exacto:',
    owners_delete_type_ph: 'Nombre exacto de la tienda',
    owners_btn_delete_confirm: 'Eliminar Definitivamente',
    owners_btn_deleting: 'Eliminando...',

    // Categories Manager
    cat_manager_badge: 'Taxonomía de Productos',
    cat_manager_title: 'Gestión de Categorías',
    cat_manager_desc: 'Crea categorías personalizadas para organizar tus productos. Las categorías del sistema son de solo lectura.',
    cat_manager_my_title: 'Mis Categorías',
    cat_manager_custom_badge: 'personalizadas',
    cat_manager_system_title: 'Categorías del Sistema',
    cat_manager_readonly_badge: 'Solo lectura',
    cat_manager_new_btn: 'Nueva Categoría',
    cat_manager_form_title: 'Nueva Categoría Personalizada',
    cat_manager_form_name: 'Nombre de la categoría *',
    cat_manager_form_name_ph: 'Ej. Temporada de Verano',
    cat_manager_form_icon: 'Ícono (emoji)',
    cat_manager_form_desc: 'Descripción breve (opcional)',
    cat_manager_form_desc_ph: 'Ej. Artículos de temporada alta',
    cat_manager_form_badge: 'Etiqueta (opcional)',
    cat_manager_form_badge_ph: 'Ej. Nuevo, Promo, Top Seller',
    cat_manager_form_cancel: 'Cancelar',
    cat_manager_form_save: 'Guardar Categoría',
    cat_manager_form_saving: 'Guardando...',
    cat_manager_empty_title: 'Aún no has creado categorías personalizadas.',
    cat_manager_empty_btn: 'Crear primera categoría →',
    cat_manager_edit_save: 'Guardar',
    cat_manager_edit_cancel: 'Cancelar',
    cat_manager_delete_confirm: 'Eliminar',
    cat_manager_delete_cancel: 'Cancelar',
    cat_manager_loading: 'Cargando categorías...',

    // Programmer Dashboard Overview
    prog_stat_owners: 'Dueños Registrados',
    prog_stat_owners_link: 'Ver directorio ›',
    prog_stat_branches: 'Sucursales Activas',
    prog_stat_branches_sub: 'Operativas',
    prog_stat_users: 'Usuarios Registrados',
    prog_stat_users_link: 'Ver tabla y claves ›',
    prog_stat_firebase: 'Firebase Admin SDK',
    prog_stat_firebase_status: 'Conectado',
    prog_stat_roles: 'Seguridad de Roles',
    prog_stat_roles_status: 'Activa',
    prog_card_prog_title: 'Equipo de Programadores',
    prog_card_prog_sub: 'Alta de desarrolladores con credenciales',
    prog_card_prog_desc: 'Crea y administra accesos de programadores con contraseñas seguras y roles especializados para colaborar en la administración de la plataforma.',
    prog_card_prog_btn: 'Gestionar Programadores',
    prog_card_owners_title: 'Directorio de Dueños',
    prog_card_owners_sub: 'Control de franquicias y tiendas',
    prog_card_owners_desc: 'Genera invitaciones con token único de 7 días, activa el modo soporte para inspeccionar la tienda como el dueño, o revoca credenciales de manera auditada.',
    prog_card_owners_btn: 'Ir a Dueños',
    prog_card_emp_title: 'Registro de Empleados',
    prog_card_emp_sub: 'Altas directas con área personalizada',
    prog_card_emp_desc: 'Crea credenciales operativas asignando áreas de trabajo estándar o personalizadas por ti para una mejor administración.',
    prog_card_emp_btn: 'Abrir Módulo de Empleados',
    prog_card_users_title: 'Directorio Central de Usuarios Registrados',
    prog_card_users_badge: 'Exclusivo Programador',
    prog_card_users_sub: 'Tabla con nombre, correo, edad, dirección, contraseña y control de modificaciones por mes y año.',
    prog_card_users_btn: 'Ver Tabla de Usuarios',
    prog_card_users_feat1_title: 'Vista en Tabla',
    prog_card_users_feat1_sub: 'Diseño responsive con columnas organizadas',
    prog_card_users_feat2_title: 'Filtro Mes y Año',
    prog_card_users_feat2_sub: 'Explora altas por fecha o período temporal',
    prog_card_users_feat3_title: 'Contraseñas & Cambios',
    prog_card_users_feat3_sub: 'Visualiza clave original o fecha de modificación',
    prog_card_users_feat4_title: 'Dirección y Edad',
    prog_card_users_feat4_sub: 'Datos de perfil y entrega de todos los usuarios',
    prog_system_title: 'Arquitectura & Servicios en Tiempo Real',
    prog_system_nextjs_status: 'Saludable (200 OK)',
    prog_system_firestore_status: 'Tiempo Real',
    prog_system_prices: 'Sistema de Precios Ocultos',
    prog_system_prices_sub: 'Los precios y botones de compra son inaccesibles para visitantes sin sesión',
    prog_system_prices_status: 'Protegido',
    prog_system_currency: 'Moneda del Sistema',
    prog_system_currency_sub: 'Córdobas Nicaragüenses (C$ / NIO) por defecto con formateo Intl',
    prog_system_currency_status: 'Configurado',
    prog_logs_title: 'Registro de Eventos y Auditoría del Sistema',
    prog_referral_desc: 'Gestiona tu enlace único de atribución como desarrollador. Toda venta originada desde tu enlace queda registrada automáticamente bajo tu perfil.',
    prog_emp_console_title: 'Consola Superadmin · Registro de Empleados',
    prog_emp_console_sub: 'Crea correos y contraseñas de empleados para cualquier sucursal y gestiona tus propias áreas de trabajo personalizadas.',
    prog_system_firestore: 'Firestore Base de Datos en Tiempo Real',
    dash_station_tools: 'Operaciones de Caja',
    dash_sale_direct: 'Nueva Venta Directa',
    dash_sale_direct_desc: 'Explorar catálogo y cobrar',
    dash_validate_delivery: 'Validar Retiro Delivery',
    dash_validate_delivery_desc: 'Generar QR para repartidor',
    dash_cash_partial: 'Corte de Caja Parcial',
    dash_cash_partial_desc: 'Reportar efectivo actual',
    dash_shift_history: 'Historial de Turno',
    dash_shift_history_desc: 'Ver cobros recientes',
    dash_warehouse_scan_desc: 'Escanear códigos y registrar inventario',
    orders_status_on_way: 'En Camino',
    orders_status_delivered: 'Entregado',
    orders_status_cancelled: 'Cancelado',
    orders_hide_items: 'Ocultar checklist de productos',
    orders_show_items: 'Ver productos a preparar',
    orders_loading_items: 'Cargando artículos...',
    orders_ready_msg: 'Listo para que el delivery escanee el QR en mostrador...',
    orders_btn_dispatch: 'Despachar (En Camino)',
    orders_btn_deliver: 'Marcar Entregado al Cliente',
    orders_btn_cancel: 'Cancelar y liberar stock',
    emp_mgr_title: 'Gestión de Personal y Estaciones de Trabajo',
    emp_mgr_sub: 'Crea empleados con credenciales seguras, asígnales sucursal y determina su área operativa.',
    emp_mgr_btn_add: 'Nuevo Empleado',
    emp_mgr_btn_areas: 'Gestionar Áreas',
    emp_mgr_search_ph: 'Buscar empleado por nombre, correo o celular...',
    emp_mgr_filter_area: 'Todas las áreas',
    emp_mgr_filter_branch: 'Todas las sucursales',
    emp_mgr_stat_total: 'Total Empleados',
    emp_mgr_stat_active: 'En Servicio',
    emp_mgr_stat_paused: 'En Pausa',
    emp_mgr_th_employee: 'EMPLEADO',
    emp_mgr_th_area: 'ÁREA / ESTACIÓN',
    emp_mgr_th_branch: 'SUCURSAL',
    emp_mgr_th_credentials: 'CREDENCIALES',
    emp_mgr_th_status: 'ESTADO',
    emp_mgr_th_actions: 'ACCIONES',
    emp_mgr_badge_custom: 'Área Personalizada',
    emp_mgr_btn_toggle_active: 'Reanudar Turno',
    emp_mgr_btn_toggle_pause: 'Pausar Turno',
    emp_mgr_btn_delete: 'Eliminar Empleado',
    emp_mgr_copied_pass: '¡Contraseña copiada!',
    emp_mgr_empty_title: 'No hay empleados registrados',
    emp_mgr_empty_desc: 'Comienza dando de alta a tu primer colaborador en la sucursal.',
    emp_mgr_empty_btn: 'Crear Primer Empleado',
    emp_mgr_modal_new_title: 'Registrar Nuevo Empleado',
    emp_mgr_modal_new_desc: 'Crea las credenciales de inicio de sesión y define su puesto operativo.',
    emp_mgr_form_name: 'Nombre Completo *',
    emp_mgr_form_name_ph: 'Ej. Juan Pérez',
    emp_mgr_form_email: 'Correo Electrónico *',
    emp_mgr_form_email_ph: 'empleado@saytamall.com',
    emp_mgr_form_pass: 'Contraseña de Acceso *',
    emp_mgr_form_pass_ph: 'Mínimo 6 caracteres',
    emp_mgr_form_pass_gen: 'Generar segura',
    emp_mgr_form_phone: 'Teléfono / WhatsApp',
    emp_mgr_form_phone_ph: 'Ej. +505 8888 8888',
    emp_mgr_form_branch: 'Sucursal de Asignación *',
    emp_mgr_form_area: 'Área de Trabajo *',
    emp_mgr_form_cancel: 'Cancelar',
    emp_mgr_form_save: 'Registrar Empleado',
    emp_mgr_form_saving: 'Registrando...',
    emp_mgr_delete_title: 'Eliminar Empleado',
    emp_mgr_delete_desc: '¿Estás seguro de que deseas eliminar este colaborador? Esta acción es irreversible.',
    emp_mgr_delete_confirm: 'Confirmar Eliminación',
    emp_mgr_delete_canceling: 'Eliminando...',
    prog_mgr_title: 'Equipo de Desarrolladores de Software',
    prog_mgr_sub: 'Administra cuentas técnicas con acceso total a la consola de desarrollo, APIs y Firestore.',
    prog_mgr_btn_add: 'Nuevo Desarrollador',
    prog_mgr_search_ph: 'Buscar programador por nombre o correo...',
    prog_mgr_th_programmer: 'PROGRAMADOR',
    prog_mgr_th_role: 'ROL TÉCNICO',
    prog_mgr_th_date: 'FECHA DE ALTA',
    prog_mgr_th_access: 'NIVEL DE ACCESO',
    prog_mgr_th_actions: 'ACCIONES',
    prog_mgr_badge_root: 'Superadmin Root',
    prog_mgr_badge_standard: 'Ingeniero Backend / Frontend',
    prog_mgr_empty_title: 'No hay programadores registrados',
    prog_mgr_empty_desc: 'Invita o crea cuentas de desarrollador para colaborar en el sistema.',
    prog_mgr_modal_title: 'Registrar Nuevo Programador',
    prog_mgr_modal_desc: 'Crea credenciales con privilegios elevados para colaborar en el desarrollo.',
    prog_mgr_form_role: 'Especialidad / Cargo Técnico',
    prog_mgr_form_role_ph: 'Ej. Desarrollador Fullstack',
    prog_mgr_form_save: 'Crear Programador',
    prog_mgr_form_saving: 'Creando cuenta...',
    audit_mgr_title: 'Auditoría de Cambios y Seguridad',
    audit_mgr_sub: 'Trazabilidad de modificaciones de precios, descuentos y catálogo en tiempo real.',
    audit_mgr_search_ph: 'Filtrar por producto, SKU o usuario...',
    audit_mgr_filter_all: 'Todas las acciones',
    audit_mgr_th_action: 'ACCIÓN',
    audit_mgr_th_details: 'PRODUCTO / DETALLES',
    audit_mgr_th_change: 'CAMBIO DE PRECIO',
    audit_mgr_th_user: 'RESPONSABLE',
    audit_mgr_th_date: 'FECHA Y HORA',
    audit_mgr_empty: 'No se encontraron eventos de auditoría con los filtros aplicados.',
    branch_mgr_title: 'Directorio de Sucursales Físicas',
    branch_mgr_sub: 'Control de sedes operativas, horarios de atención, teléfonos y métodos de despacho.',
    branch_mgr_btn_edit: 'Editar Sucursal',
    branch_mgr_btn_delete: 'Eliminar Sucursal',
    branch_mgr_btn_save: 'Guardar Sucursal',
    branch_mgr_btn_saving: 'Guardando...',
    branch_mgr_field_name: 'Nombre de Sucursal',
    branch_mgr_field_address: 'Dirección Completa',
    branch_mgr_field_city: 'Ciudad / Municipio',
    branch_mgr_field_phone: 'Teléfono Principal',
    branch_mgr_field_whatsapp: 'WhatsApp de Contacto',
    branch_mgr_field_schedule: 'Horario de Atención',
    branch_mgr_field_currency: 'Moneda de Caja',
    branch_mgr_field_delivery: 'Modalidad de Entrega',
    branch_mgr_delivery_both: 'Retiro en Tienda y Envíos',
    branch_mgr_delivery_pickup: 'Solo Retiro en Mostrador',
    branch_mgr_delivery_ship: 'Solo Envíos a Domicilio',
    branch_mgr_empty_title: 'No hay sucursales registradas',
    branch_mgr_empty_desc: 'Crea tu primera sucursal para activar las ventas y asignación de personal.',
    users_reg_title: 'Directorio Central de Usuarios del Sistema',
    users_reg_sub: 'Base unificada de clientes, empleados, dueños y desarrolladores registrados en la plataforma.',
    users_reg_search_ph: 'Buscar usuario por nombre, correo o celular...',
    users_reg_filter_role: 'Todos los roles',
    users_reg_filter_month: 'Mes de registro',
    users_reg_filter_year: 'Año de registro',
    users_reg_th_user: 'USUARIO',
    users_reg_th_role: 'ROL',
    users_reg_th_contact: 'CONTACTO',
    users_reg_th_location: 'UBICACIÓN Y EDAD',
    users_reg_th_credentials: 'CREDENCIALES',
    users_reg_th_date: 'FECHA DE REGISTRO',
    users_reg_th_actions: 'ACCIONES',
    users_reg_btn_refresh: 'Actualizar',
    users_reg_btn_export: 'Descargar CSV',
    users_reg_empty: 'No se encontraron usuarios que coincidan con la búsqueda.',
    users_reg_copied_pass: 'Contraseña copiada al portapapeles',
    branch_qr_title: 'Gestor Central de Códigos QR de Sucursal',
    branch_qr_sub: 'Genera y administra códigos QR dinámicos para retiro y validación de pedidos en mostrador.',
    branch_qr_btn_rotate: 'Rotar Token Ahora',
    branch_qr_btn_download: 'Descargar Imagen',
    branch_qr_btn_print: 'Imprimir Cartel',
    branch_qr_btn_fullscreen: 'Pantalla Completa',
    branch_qr_mode_dynamic: 'Código Dinámico (Alta Seguridad)',
    branch_qr_mode_fixed: 'Código Fijo para Mostrador',
    branch_qr_expiry_label: 'Expira en',
    branch_qr_history_title: 'Historial Reciente de Escaneos',
    branch_qr_history_empty: 'Aún no hay escaneos registrados para este código QR.',
    ref_panel_title: 'Programa de Atribución y Referidos',
    ref_panel_sub: 'Comparte tu enlace exclusivo para acreditar ventas y comisiones a tu cuenta.',
    ref_panel_copy_btn: 'Copiar Enlace',
    ref_panel_copied: '¡Enlace Copiado!',
    ref_panel_link_label: 'Tu Enlace de Atribución Personal',
    ref_panel_total_sales: 'Ventas Atribuidas',
    ref_panel_commissions: 'Comisiones Generadas',
    ref_panel_note: 'Cualquier cliente que compre mediante este enlace quedará asociado a tu perfil.',

  },
  en: {
    // Navigation
    nav_dashboard_programmer: 'Command Center',
    nav_dashboard_owner: 'Executive Dashboard',
    nav_dashboard_employee: 'My Station',
    nav_chat_team: 'Team Chat',
    nav_chat_staff: 'Staff Chat',
    nav_products: 'Product Management',
    nav_categories: 'Categories',
    nav_owners: 'Store Owners',
    nav_employees: 'Employee Management',
    nav_delivery: 'Delivery Companies',
    nav_catalog: 'Store Catalog',
    nav_settings: 'Dashboard Settings',

    // Settings
    settings_title: 'Dashboard Settings',
    settings_subtitle: 'Customize the visual theme and language exclusively for your session.',
    settings_notice: 'These settings apply only to your account and do not affect the public storefront or other staff members.',
    settings_theme_label: 'Dashboard Visual Theme',
    settings_lang_label: 'Dashboard Language',
    settings_lang_es: 'Spanish (Latin America)',
    settings_lang_en: 'English (United States)',
    settings_lang_zh: 'Chinese (Simplified)',
    settings_applied: 'Preferences updated successfully!',

    // Common actions and status
    btn_save: 'Save Settings',
    btn_close: 'Close',
    btn_open_chat: 'Open Messenger',
    btn_copy_link: 'Copy Link',
    btn_pause_shift: 'Pause Shift',
    btn_resume_shift: 'Resume Shift',
    status_on_duty: 'On Duty',
    status_paused: 'Paused',
    status_connected: 'Online',
    search_placeholder: 'Search...',
    logout: 'Sign Out',
    verify_phone: 'Verify Phone',
    change_branch: 'Change Branch',
    no_branches: 'No branches',

    // Mobile Dock and Badges
    tab_summary: 'Summary',
    tab_products: 'Products',
    tab_chat: 'Chat',
    tab_owners: 'Owners',
    tab_delivery: 'Delivery',
    tab_menu: 'Menu',
    tab_station: 'My Station',
    tab_store: 'Store',
    tab_employees: 'Employees',
    back_to_store: 'Back to Store',
    view_public_store: 'View Public Store',
    collapse_sidebar: 'Collapse sidebar',
    expand_sidebar: 'Expand sidebar',
    superadmin: 'Superadmin',
    role_owner: 'Owner',
    role_employee: 'Employee',
    role_programmer: 'Programmer',
    badge_live: 'Live',
    badge_inventory: 'Inventory',
    badge_catalog: 'Catalog',
    badge_management: 'Management',
    badge_shipping: 'Shipping',

    // Employee Dashboard
    dash_active_station: 'Active Station',
    dash_branch_main: 'Main Branch',
    dash_welcome: 'Welcome',
    dash_employee_subtitle: 'Operational panel adapted to your duties of',
    dash_shift_status: 'Shift Status',
    dash_on_duty_label: 'On Duty',
    dash_on_pause_label: 'On Pause',
    dash_tab_orders_qr: 'Orders & QR Validation',
    dash_tab_station_tools: 'Station Tools',
    dash_tab_referral: 'My Referral Link',
    dash_collaborative_title: 'Upload and Manage Store Products',
    dash_collaborative_desc: 'Collaborate by adding new products, prices, descriptions, and categories. Submit discounts for Owner or Developer authorization.',
    dash_manage_products_btn: 'Manage Products',
    dash_internal_chat_title: 'Internal Staff Chat',
    dash_internal_chat_desc: 'Communicate instantly with on-duty coworkers, coordinate register handovers, report urgent alerts, or check stock availability.',
    dash_open_chat_btn: 'Open Chat',
    dash_cashier_opening: 'Cash Register Opening',
    dash_cashier_opening_note: 'Initial fund confirmed',
    dash_cashier_sales_today: 'Collections (Today)',
    dash_cashier_sales_waiting: 'Waiting for first transactions',
    dash_cashier_tickets: 'Receipts Issued',
    dash_cashier_tickets_note: 'Current shift',
    dash_warehouse_received: 'Goods Received',
    dash_warehouse_received_note: 'Last 7 days',
    dash_warehouse_low_stock: 'Low Stock Alerts',
    dash_warehouse_low_stock_note: 'Action recommended',
    dash_warehouse_transfers: 'Branch Transfers',
    dash_warehouse_transfers_note: 'Pending movements',
    dash_general_active_tasks: 'Active Tasks',
    dash_general_tasks_assigned: 'Assigned today',
    dash_general_urgent_alerts: 'Urgent Alerts',
    dash_general_all_clear: 'All clear',
    dash_general_branch: 'Operating Branch',

    // QR Generator Panel
    qr_panel_title: 'Delivery QR Code',
    qr_panel_desc: 'The delivery driver scans this code upon arrival at {branch} to validate the order and record payment.',
    qr_type_dynamic: 'Dynamic (2 min)',
    qr_type_fixed: 'Fixed (Counter)',
    qr_security_flow: 'Security Flow',
    qr_step_1: 'The driver arrives at the counter and scans this QR with their phone camera.',
    qr_step_2: 'Enters their name and selects delivery company (no password required).',
    qr_step_3: 'Selects the customer from the pending orders list.',
    qr_step_4: 'Reviews merchandise and registers payment to complete handoff.',
    qr_direct_link: 'Direct validation link',
    qr_btn_regenerate: 'Regenerate QR Code Now',
    qr_auto_refresh: 'Auto-refreshes in',
    qr_generating: 'Generating QR...',
    qr_copied: 'Link copied!',

    // Orders Panel
    orders_title: 'Order Monitor',
    orders_inbox: 'Message Inbox',
    orders_live: 'Firestore live',
    orders_tab_all: 'All',
    orders_tab_pending: 'Pending',
    orders_tab_preparing: 'Preparing',
    orders_tab_waiting: 'Waiting on Customer',
    orders_tab_ready: 'Ready for QR',
    orders_tab_validated: 'Validated',
    orders_empty_title: 'No orders in this category',
    orders_empty_desc: 'New orders will automatically appear here.',
    orders_card_order: 'Order',
    orders_card_customer: 'Customer',
    orders_card_total: 'Total',
    orders_card_items: 'items',
    orders_btn_prepare: 'Start Preparing',
    orders_btn_missing: 'Missing Item',
    orders_btn_ready: 'Ready for Handoff',
    orders_btn_chat: 'Customer Chat',

    // Dueño Dashboard
    owner_portal_badge: 'Owner Executive Portal',
    owner_active_branches: 'Active Branches',
    owner_dashboard_title: 'Store Control Panel',
    owner_dashboard_desc: 'Manage branches, oversee staff, and track customer orders in real time.',
    owner_btn_new_branch: 'New Branch',
    owner_btn_products: 'Products & Discounts',
    owner_btn_employees: 'Manage Staff',
    owner_tab_orders: 'Orders & Delivery',
    owner_tab_qr: 'Branch QR Codes',
    owner_tab_branches: 'Branches',
    owner_tab_metrics: 'Sales & Metrics',
    owner_stat_sales_today: "Today's Sales",
    owner_stat_pending_orders: 'Pending Orders',
    owner_stat_active_products: 'Active Products',
    owner_stat_active_staff: 'On-duty Staff',

    // Programador Dashboard
    prog_console_badge: 'Developer Main Console',
    prog_superadmin: 'SUPERADMIN ACCESS',
    prog_title: 'Master Control Panel',
    prog_desc: 'Full monitoring of Firebase Auth, programmer team, privileged roles, owner invites, and employee registry.',
    prog_btn_add_prog: '+ Programmers',
    prog_btn_delivery: 'Delivery',
    prog_btn_owners: 'Owners',
    prog_tab_overview: 'Overview',
    prog_tab_programmers: 'Programmers Team',
    prog_tab_owners: 'Owners & Managers',
    prog_tab_delivery: 'Delivery Companies',
    prog_tab_employees: 'Employee Registry',
    prog_tab_audit: 'Audit Log',
    prog_tab_database: 'RTDB Database',

    // Areas
    area_caja: 'Cashier',
    area_bodega: 'Warehouse',
    area_empaque: 'Packaging',
    area_cocina: 'Kitchen',
    area_despacho: 'Dispatch',
    area_general: 'General',

    // Referral
    ref_title: 'My Referral Link',
    ref_desc: 'Share your link or QR code to receive commission credit for each purchase made.',

    // Products & Inventory
    prod_module_badge: 'Unified Inventory Module',
    prod_management_title: 'Products & Discounts Management',
    prod_management_desc: 'Owner and employees can upload products with prices, descriptions, and categories. Employee discounts require authorization from the Owner or Programmer before showing in the public store.',
    prod_btn_new_category: 'New Category',
    prod_btn_add_product: 'Add Product',
    prod_pending_discounts_title: 'Discount Requests Pending Authorization',
    prod_can_authorize: 'You have permissions to approve or reject these discounts',
    prod_waiting_review: 'Waiting for review by Owner or Programmer',
    prod_discount_reason: 'Reason',
    prod_proposed_by: 'Proposed by',
    prod_btn_approve: 'Approve Discount',
    prod_btn_reject: 'Reject',
    prod_pending_badge: 'Pending authorization',
    prod_search_placeholder: 'Search by name, category or description...',
    prod_filter_all_cats: 'All Categories',
    prod_filter_all_status: 'All Status',
    prod_filter_discounted: 'Active Discount',
    prod_filter_pending: 'Pending Discounts',
    prod_empty_title: 'No products in this view',
    prod_empty_desc: 'You can add new products with prices, descriptions and categories using the button above.',
    prod_btn_add_first: 'Add First Product',
    prod_card_edit: 'Edit',
    prod_card_discount: 'Discount',
    prod_card_barcode: 'Barcode',
    prod_card_in_stock: 'In stock',
    prod_card_low_stock: 'Low stock',
    prod_card_out_of_stock: 'Out of stock',
    prod_cat_tools: 'Hardware & Tools',
    prod_cat_shoes: 'Footwear & Shoes',
    prod_cat_clothing: 'Clothing & Fashion',
    prod_cat_lingerie: 'Intimate Apparel & Shapewear',
    prod_cat_cosmetics: 'Cosmetics & Beauty',
    prod_cat_electronics: 'Electronics & Gadgets',
    prod_cat_snacks: 'Chinese Snacks & Foods',
    prod_cat_caps: 'Hats & Accessories',
    prod_cat_home: 'Home & Kitchen',
    prod_cat_seasonal: 'Seasonal Products',
    prod_cat_adult: 'Adult Products',
    prod_cat_general: 'General',

    // Chat
    chat_title: 'Staff Internal Chat',
    chat_desc: 'Communicate in real time with branch colleagues, check stock and coordinate shifts.',
    chat_search_placeholder: 'Search channel or coworker...',
    chat_team_rooms: 'Team Channels',
    chat_coworkers: 'On-Duty Coworkers',
    chat_no_coworkers: 'No coworkers found.',
    chat_on_shift: 'On duty',
    chat_active_channel: 'Active Channel',
    chat_syncing: 'Syncing channel messages...',
    chat_empty_title: 'No messages yet in this channel',
    chat_empty_desc: 'Be the first to write! You can check stock, coordinate shifts or notify colleagues.',
    chat_urgent_badge: 'URGENT NOTICE',
    chat_shift_badge: 'SHIFT HANDOVER',
    chat_stock_badge: 'STOCK INQUIRY',
    chat_quick_tags: 'Quick Tags:',
    chat_tag_urgent: 'Urgent',
    chat_tag_shift: 'Shift',
    chat_tag_stock: 'Stock',
    chat_placeholder_urgent: 'Write a priority or urgent alert...',
    chat_placeholder_shift: 'Report shift start, handoff or break...',
    chat_placeholder_stock: 'Ask or notify about product inventory...',
    chat_placeholder_general: 'Message for',
    chat_btn_send: 'Send',
    chat_ch_general: 'Team General Hall',
    chat_ch_general_desc: 'Store-wide announcements and notices',
    chat_ch_ferreteria: 'Hardware & Counter',
    chat_ch_ferreteria_desc: 'Tool inquiries, prices, specifications and stock',
    chat_ch_caja: 'Cashier & Billing',
    chat_ch_caja_desc: 'Shift settlements, receipts, invoices and sales confirmations',
    chat_ch_bodega: 'Warehouse & Dispatch',
    chat_ch_bodega_desc: 'Inventory control, package receipt and order fulfillment',

    // Owner Dashboard Extra
    owner_onboarding_required: 'Initial Setup Required',
    owner_onboarding_welcome: 'Welcome to Sayta Mall',
    owner_onboarding_desc: 'To start receiving orders and registering employees, create your first operational branch.',
    owner_stat_active_branch: 'Active Branch',
    owner_stat_online: 'Online',
    owner_stat_currency: 'Operating Currency',
    owner_stat_currency_local: 'Local standard',
    owner_stat_dispatch: 'Dispatch',
    owner_stat_enabled: 'Enabled',
    owner_stat_staff: 'Staff',
    owner_stat_active: 'Active',
    owner_stat_manager_avail: 'Manager available',
    owner_card_employees_title: 'Employee & Shift Management',
    owner_card_employees_desc: 'Add employee credentials, assign them to branches and areas (Cashier, Warehouse, Sales, Cleaning, Service, or General).',
    owner_card_employees_btn: 'Open Staff & Areas Manager',
    owner_card_products_title: 'Catalog & Discounts',
    owner_card_products_desc: 'Supervise products uploaded by your staff and approve promotions or discounts suggested for your branch.',
    owner_card_products_btn: 'Manage Products',
    owner_registered_branches: 'registered',
    owner_referral_program: 'My Referral Program',
    owner_single_branch_active: 'Active Branch',
    owner_multi_branch_active: 'Active Branches',

    // Programmer Dashboard Extra
    prog_tab_staff: 'Workers & Employees',
    prog_tab_system: 'System Health',
    prog_tab_logs: 'Audit Logs',
    prog_tab_audit_staff: 'Staff Audit',
    prog_tab_users: 'Registered Users',
    prog_tab_referral: 'Developer Referral Link',
    prog_tab_cronjobs: 'Cron Jobs',
    prog_tab_qr_branch: 'Branch QR Codes',

    // Report Missing Item Modal
    missing_modal_title: 'Report Unavailable Product',
    missing_modal_desc: 'By marking products as unavailable, the order will switch to Customer Wait and lock for delivery. A live chat with decision options will open.',
    missing_btn_notify: 'Pause & Notify Customer',
    missing_btn_add_another: 'Add another missing item',
    missing_opt_out_of_stock: 'Out of stock at branch',
    missing_opt_damaged: 'Damaged or expired unit',
    missing_opt_inventory_diff: 'Inventory discrepancy',
    missing_suggest_title: 'Suggest alternative (Optional)',
    missing_substitute_name: 'Substitute product name',
    missing_substitute_price: 'Suggested price',

    // Delivery Page
    delivery_badge: 'Logistics & Distribution',
    delivery_live_badge: 'LIVE',
    delivery_title: 'Delivery / Shipping Companies',
    delivery_desc: 'Register and manage local courier companies. Customers can select them at checkout and send orders directly via WhatsApp or through the web.',
    delivery_btn_register: 'Register Company',
    delivery_stat_total: 'Total Companies',
    delivery_stat_total_sub: 'Registered in system',
    delivery_stat_active: 'Active at Checkout',
    delivery_stat_active_sub: 'Available to customers',
    delivery_stat_zones: 'Coverage Zones',
    delivery_stat_zones_sub: 'Active delivery areas',
    delivery_stat_orders: 'Routed Orders',
    delivery_stat_orders_sub: 'Via Web & WhatsApp',
    delivery_search_placeholder: 'Search by name, WhatsApp or zone...',
    delivery_filter_all: 'All',
    delivery_filter_active: 'Active',
    delivery_filter_inactive: 'Inactive',
    delivery_loading: 'Loading delivery companies...',
    delivery_empty_title: 'No delivery companies found',
    delivery_empty_search: 'No company matches the search. Try a different term.',
    delivery_empty_first: 'Register your first delivery company so customers can select it at checkout.',
    delivery_btn_register_now: 'Register Company Now',
    delivery_active_label: 'Active at Checkout',
    delivery_inactive_label: 'Inactive (Hidden)',
    delivery_rate_label: 'Shipping Rate',
    delivery_rate_value: 'By Destination',
    delivery_zones_label: 'Coverage zones',
    delivery_orders_label: 'Orders',
    delivery_btn_test: 'Test WhatsApp',
    delivery_btn_edit: 'Edit',
    delivery_btn_toggle_active: 'Activate company',
    delivery_btn_toggle_inactive: 'Deactivate company',
    delivery_btn_delete: 'Delete company',
    delivery_modal_create_title: 'Register New Delivery Company',
    delivery_modal_edit_title: 'Edit Delivery Company',
    delivery_form_name: 'Company name *',
    delivery_form_name_placeholder: 'e.g. Moto Express Chichigalpa',
    delivery_form_whatsapp: 'International WhatsApp *',
    delivery_form_phone: 'Conventional phone (optional)',
    delivery_form_email: 'Email address (optional)',
    delivery_form_zones: 'Coverage zones (comma separated) *',
    delivery_form_zones_placeholder: 'e.g. Downtown, San Antonio Estate, El Carmen District',
    delivery_form_logo: 'Logo URL (optional)',
    delivery_form_status: 'Status: Active at Checkout',
    delivery_btn_cancel: 'Cancel',
    delivery_btn_save: 'Save Changes',
    delivery_btn_create: 'Register Company',
    delivery_btn_submitting: 'Saving...',
    delivery_delete_title: 'Delete Delivery Company',
    delivery_delete_desc: 'Are you sure you want to delete',
    delivery_delete_warning: 'This action may deactivate it if it has associated orders.',
    delivery_btn_delete_confirm: 'Yes, delete company',
    delivery_btn_deleting: 'Deleting...',

    // Owners Management Page
    owners_badge: 'Superadmin Console',
    owners_count_label: 'Registered Owners',
    owners_title: 'Store Owner Management',
    owners_desc: 'Manage franchise and store owner access. Invite them via email, temporarily suspend access, use support mode to assist them, or delete records with two-step confirmation.',
    owners_btn_add: 'Add Owner',
    owners_search_placeholder: 'Search by name, email or store name...',
    owners_col_owner: 'Owner & Email',
    owners_col_store: 'Assigned Store',
    owners_col_branches: 'Branches',
    owners_col_status: 'Status',
    owners_col_date: 'Registration Date',
    owners_col_actions: 'Actions',
    owners_status_active: 'Active',
    owners_status_suspended: 'Suspended',
    owners_status_pending: '7d Pending',
    owners_invite_pending: 'Invitation pending',
    owners_branches_label: 'branch',
    owners_branches_plural: 'branches',
    owners_btn_view: 'View owner panel',
    owners_btn_support: 'Support mode',
    owners_btn_suspend: 'Suspend access',
    owners_btn_restore: 'Restore access',
    owners_btn_delete: 'Delete owner',
    owners_empty_title: 'No owners registered yet',
    owners_empty_desc: 'Add the first franchise owner with their email and password to get started.',
    owners_modal_title: 'Register New Store Owner',
    owners_modal_desc: 'Create the owner access credentials. A welcome email will be sent automatically with login instructions.',
    owners_form_name: 'Owner name *',
    owners_form_name_ph: 'e.g. Xia Xue',
    owners_form_email: 'Email address *',
    owners_form_email_ph: 'owner@example.com',
    owners_form_store: 'Store name *',
    owners_form_store_ph: 'e.g. Sayta Mall Chichigalpa',
    owners_form_password: 'Temporary password *',
    owners_form_password_ph: 'Minimum 6 characters',
    owners_form_branch: 'Assign Branch(es)',
    owners_btn_create: 'Register Owner',
    owners_btn_creating: 'Registering...',
    owners_delete_title: 'Delete Store Owner',
    owners_delete_desc: 'This action is irreversible. Type the exact store name to confirm:',
    owners_delete_type_label: 'Type exact name:',
    owners_delete_type_ph: 'Exact store name',
    owners_btn_delete_confirm: 'Delete Permanently',
    owners_btn_deleting: 'Deleting...',

    // Categories Manager
    cat_manager_badge: 'Product Taxonomy',
    cat_manager_title: 'Category Management',
    cat_manager_desc: 'Create custom categories to organize your products. System categories are read-only.',
    cat_manager_my_title: 'My Categories',
    cat_manager_custom_badge: 'custom',
    cat_manager_system_title: 'System Categories',
    cat_manager_readonly_badge: 'Read only',
    cat_manager_new_btn: 'New Category',
    cat_manager_form_title: 'New Custom Category',
    cat_manager_form_name: 'Category name *',
    cat_manager_form_name_ph: 'e.g. Summer Season',
    cat_manager_form_icon: 'Icon (emoji)',
    cat_manager_form_desc: 'Short description (optional)',
    cat_manager_form_desc_ph: 'e.g. High season products',
    cat_manager_form_badge: 'Label (optional)',
    cat_manager_form_badge_ph: 'e.g. New, Promo, Top Seller',
    cat_manager_form_cancel: 'Cancel',
    cat_manager_form_save: 'Save Category',
    cat_manager_form_saving: 'Saving...',
    cat_manager_empty_title: 'You have not created any custom categories yet.',
    cat_manager_empty_btn: 'Create first category →',
    cat_manager_edit_save: 'Save',
    cat_manager_edit_cancel: 'Cancel',
    cat_manager_delete_confirm: 'Delete',
    cat_manager_delete_cancel: 'Cancel',
    cat_manager_loading: 'Loading categories...',

    // Programmer Dashboard Overview
    prog_stat_owners: 'Registered Owners',
    prog_stat_owners_link: 'View directory ›',
    prog_stat_branches: 'Active Branches',
    prog_stat_branches_sub: 'Operational',
    prog_stat_users: 'Registered Users',
    prog_stat_users_link: 'View table & credentials ›',
    prog_stat_firebase: 'Firebase Admin SDK',
    prog_stat_firebase_status: 'Connected',
    prog_stat_roles: 'Role Security',
    prog_stat_roles_status: 'Active',
    prog_card_prog_title: 'Programmer Team',
    prog_card_prog_sub: 'Developer account creation',
    prog_card_prog_desc: 'Create and manage programmer access with secure passwords and specialized roles to collaborate in platform administration.',
    prog_card_prog_btn: 'Manage Programmers',
    prog_card_owners_title: 'Owner Directory',
    prog_card_owners_sub: 'Franchise and store control',
    prog_card_owners_desc: 'Generate 7-day token invitations, activate support mode to inspect the store as the owner, or revoke credentials with full audit trail.',
    prog_card_owners_btn: 'Go to Owners',
    prog_card_emp_title: 'Employee Registry',
    prog_card_emp_sub: 'Direct enrollment with custom area',
    prog_card_emp_desc: 'Create operational credentials assigning standard or custom work areas for better management.',
    prog_card_emp_btn: 'Open Employee Module',
    prog_card_users_title: 'Central Directory of Registered Users',
    prog_card_users_badge: 'Programmer Exclusive',
    prog_card_users_sub: 'Table with name, email, age, address, password and modification control by month and year.',
    prog_card_users_btn: 'View Users Table',
    prog_card_users_feat1_title: 'Table View',
    prog_card_users_feat1_sub: 'Responsive design with organized columns',
    prog_card_users_feat2_title: 'Month & Year Filter',
    prog_card_users_feat2_sub: 'Explore registrations by date or time period',
    prog_card_users_feat3_title: 'Passwords & Changes',
    prog_card_users_feat3_sub: 'View original password or date of change',
    prog_card_users_feat4_title: 'Address & Age',
    prog_card_users_feat4_sub: 'Profile and delivery data for all users',
    prog_system_title: 'Architecture & Real-Time Services',
    prog_system_nextjs_status: 'Healthy (200 OK)',
    prog_system_firestore_status: 'Real Time',
    prog_system_prices: 'Hidden Pricing System',
    prog_system_prices_sub: 'Prices and checkout buttons are inaccessible to unauthenticated visitors',
    prog_system_prices_status: 'Protected',
    prog_system_currency: 'System Currency',
    prog_system_currency_sub: 'Nicaraguan Cordobas (C$ / NIO) by default with Intl formatting',
    prog_system_currency_status: 'Configured',
    prog_logs_title: 'System Event Log & Audit',
    prog_referral_desc: 'Manage your unique attribution link as developer. Every sale from your link is automatically logged under your profile.',
    prog_emp_console_title: 'Superadmin Console · Employee Registry',
    prog_emp_console_sub: 'Create employee emails and passwords for any branch and manage your own custom work areas.',
    prog_system_firestore: 'Firestore Realtime Database',
    dash_station_tools: 'Cashier Operations',
    dash_sale_direct: 'New Direct Sale',
    dash_sale_direct_desc: 'Browse catalog and checkout',
    dash_validate_delivery: 'Validate Delivery Pickup',
    dash_validate_delivery_desc: 'Generate QR for courier',
    dash_cash_partial: 'Partial Cash Count',
    dash_cash_partial_desc: 'Report current cash balance',
    dash_shift_history: 'Shift History',
    dash_shift_history_desc: 'View recent transactions',
    dash_warehouse_scan_desc: 'Scan barcodes and update inventory',
    orders_status_on_way: 'On the Way',
    orders_status_delivered: 'Delivered',
    orders_status_cancelled: 'Cancelled',
    orders_hide_items: 'Hide product checklist',
    orders_show_items: 'View items to prepare',
    orders_loading_items: 'Loading items...',
    orders_ready_msg: 'Ready for courier to scan QR at counter...',
    orders_btn_dispatch: 'Dispatch (On the Way)',
    orders_btn_deliver: 'Mark Delivered to Customer',
    orders_btn_cancel: 'Cancel and return stock',
    emp_mgr_title: 'Staff Management & Workstations',
    emp_mgr_sub: 'Create employees with secure credentials, assign branches, and define operational roles.',
    emp_mgr_btn_add: 'New Employee',
    emp_mgr_btn_areas: 'Manage Work Areas',
    emp_mgr_search_ph: 'Search employee by name, email or phone...',
    emp_mgr_filter_area: 'All areas',
    emp_mgr_filter_branch: 'All branches',
    emp_mgr_stat_total: 'Total Staff',
    emp_mgr_stat_active: 'On Duty',
    emp_mgr_stat_paused: 'Paused',
    emp_mgr_th_employee: 'EMPLOYEE',
    emp_mgr_th_area: 'AREA / STATION',
    emp_mgr_th_branch: 'BRANCH',
    emp_mgr_th_credentials: 'CREDENTIALS',
    emp_mgr_th_status: 'STATUS',
    emp_mgr_th_actions: 'ACTIONS',
    emp_mgr_badge_custom: 'Custom Area',
    emp_mgr_btn_toggle_active: 'Resume Shift',
    emp_mgr_btn_toggle_pause: 'Pause Shift',
    emp_mgr_btn_delete: 'Delete Employee',
    emp_mgr_copied_pass: 'Password copied!',
    emp_mgr_empty_title: 'No registered employees',
    emp_mgr_empty_desc: 'Start by registering your first staff member in a branch.',
    emp_mgr_empty_btn: 'Create First Employee',
    emp_mgr_modal_new_title: 'Register New Employee',
    emp_mgr_modal_new_desc: 'Create login credentials and designate their operational station.',
    emp_mgr_form_name: 'Full Name *',
    emp_mgr_form_name_ph: 'e.g. John Doe',
    emp_mgr_form_email: 'Email Address *',
    emp_mgr_form_email_ph: 'employee@saytamall.com',
    emp_mgr_form_pass: 'Access Password *',
    emp_mgr_form_pass_ph: 'Min 6 characters',
    emp_mgr_form_pass_gen: 'Generate secure',
    emp_mgr_form_phone: 'Phone / WhatsApp',
    emp_mgr_form_phone_ph: 'e.g. +505 8888 8888',
    emp_mgr_form_branch: 'Assigned Branch *',
    emp_mgr_form_area: 'Work Area *',
    emp_mgr_form_cancel: 'Cancel',
    emp_mgr_form_save: 'Register Employee',
    emp_mgr_form_saving: 'Registering...',
    emp_mgr_delete_title: 'Delete Employee',
    emp_mgr_delete_desc: 'Are you sure you want to delete this staff member? This action cannot be undone.',
    emp_mgr_delete_confirm: 'Confirm Deletion',
    emp_mgr_delete_canceling: 'Deleting...',
    prog_mgr_title: 'Software Developer Team',
    prog_mgr_sub: 'Manage technical accounts with full access to the development console, APIs and database.',
    prog_mgr_btn_add: 'New Developer',
    prog_mgr_search_ph: 'Search programmer by name or email...',
    prog_mgr_th_programmer: 'PROGRAMMER',
    prog_mgr_th_role: 'TECH ROLE',
    prog_mgr_th_date: 'JOIN DATE',
    prog_mgr_th_access: 'ACCESS LEVEL',
    prog_mgr_th_actions: 'ACTIONS',
    prog_mgr_badge_root: 'Root Superadmin',
    prog_mgr_badge_standard: 'Backend / Frontend Engineer',
    prog_mgr_empty_title: 'No programmers registered',
    prog_mgr_empty_desc: 'Invite or create developer accounts to collaborate on the platform.',
    prog_mgr_modal_title: 'Register New Programmer',
    prog_mgr_modal_desc: 'Create credentials with elevated privileges to collaborate on development.',
    prog_mgr_form_role: 'Specialty / Role Title',
    prog_mgr_form_role_ph: 'e.g. Fullstack Developer',
    prog_mgr_form_save: 'Create Programmer',
    prog_mgr_form_saving: 'Creating account...',
    audit_mgr_title: 'Security & Change Audit Log',
    audit_mgr_sub: 'Real-time traceability of price modifications, automatic discounts and catalog updates.',
    audit_mgr_search_ph: 'Filter by product, SKU or user...',
    audit_mgr_filter_all: 'All actions',
    audit_mgr_th_action: 'ACTION',
    audit_mgr_th_details: 'PRODUCT / DETAILS',
    audit_mgr_th_change: 'PRICE CHANGE',
    audit_mgr_th_user: 'RESPONSIBLE USER',
    audit_mgr_th_date: 'DATE & TIME',
    audit_mgr_empty: 'No audit events found matching the selected filters.',
    branch_mgr_title: 'Physical Store Branches Directory',
    branch_mgr_sub: 'Management of store locations, working hours, phone contacts and delivery policies.',
    branch_mgr_btn_edit: 'Edit Branch',
    branch_mgr_btn_delete: 'Delete Branch',
    branch_mgr_btn_save: 'Save Branch',
    branch_mgr_btn_saving: 'Saving...',
    branch_mgr_field_name: 'Branch Name',
    branch_mgr_field_address: 'Full Street Address',
    branch_mgr_field_city: 'City / Municipality',
    branch_mgr_field_phone: 'Primary Phone',
    branch_mgr_field_whatsapp: 'WhatsApp Contact',
    branch_mgr_field_schedule: 'Business Hours',
    branch_mgr_field_currency: 'Till Currency',
    branch_mgr_field_delivery: 'Fulfillment Type',
    branch_mgr_delivery_both: 'Store Pickup & Home Delivery',
    branch_mgr_delivery_pickup: 'Store Pickup Only',
    branch_mgr_delivery_ship: 'Home Delivery Only',
    branch_mgr_empty_title: 'No registered branches',
    branch_mgr_empty_desc: 'Set up your first store branch to enable sales and employee assignments.',
    users_reg_title: 'Central System Users Directory',
    users_reg_sub: 'Unified database of all clients, staff, owners, and developers registered on the platform.',
    users_reg_search_ph: 'Search user by name, email or phone...',
    users_reg_filter_role: 'All roles',
    users_reg_filter_month: 'Registration month',
    users_reg_filter_year: 'Registration year',
    users_reg_th_user: 'USER',
    users_reg_th_role: 'ROLE',
    users_reg_th_contact: 'CONTACT',
    users_reg_th_location: 'LOCATION & AGE',
    users_reg_th_credentials: 'CREDENTIALS',
    users_reg_th_date: 'REGISTRATION DATE',
    users_reg_th_actions: 'ACTIONS',
    users_reg_btn_refresh: 'Refresh',
    users_reg_btn_export: 'Download CSV',
    users_reg_empty: 'No users match your search query.',
    users_reg_copied_pass: 'Password copied to clipboard',
    branch_qr_title: 'Store Branch QR Codes Manager',
    branch_qr_sub: 'Generate and manage dynamic QR codes for in-store pickup and order validation.',
    branch_qr_btn_rotate: 'Rotate Token Now',
    branch_qr_btn_download: 'Download Image',
    branch_qr_btn_print: 'Print Poster',
    branch_qr_btn_fullscreen: 'Fullscreen View',
    branch_qr_mode_dynamic: 'Dynamic QR (High Security)',
    branch_qr_mode_fixed: 'Fixed QR for Counter',
    branch_qr_expiry_label: 'Expires in',
    branch_qr_history_title: 'Recent QR Scan History',
    branch_qr_history_empty: 'No scans have been recorded for this QR code yet.',
    ref_panel_title: 'Referral & Attribution Program',
    ref_panel_sub: 'Share your exclusive link to credit sales and commissions directly to your account.',
    ref_panel_copy_btn: 'Copy Link',
    ref_panel_copied: 'Link Copied!',
    ref_panel_link_label: 'Your Personal Attribution Link',
    ref_panel_total_sales: 'Attributed Sales',
    ref_panel_commissions: 'Commissions Earned',
    ref_panel_note: 'Any customer who purchases via this link will be automatically attributed to your account.',

  },
  zh: {
    // 导航
    nav_dashboard_programmer: '开发控制中枢',
    nav_dashboard_owner: '店长管理后台',
    nav_dashboard_employee: '员工工作台',
    nav_chat_team: '团队通讯聊天',
    nav_chat_staff: '员工群聊',
    nav_products: '商品与折扣管理',
    nav_categories: '商品分类管理',
    nav_owners: '商户店长管理',
    nav_employees: '员工团队管理',
    nav_delivery: '外送物流公司',
    nav_catalog: '商城商品目录',
    nav_settings: '工作台个人设置',

    // 设置
    settings_title: '工作台个性化设置',
    settings_subtitle: '为您当前登录账号自定义专属视觉主题与工作语言。',
    settings_notice: '此配置仅在您的个人会话中生效，不会影响商城前台公开界面或其他同事的后台面板。',
    settings_theme_label: '工作台视觉主题',
    settings_lang_label: '工作台系统语言',
    settings_lang_es: '西班牙语 (Español)',
    settings_lang_en: '英语 (English)',
    settings_lang_zh: '中文 (简体中文)',
    settings_applied: '个人偏好设置已成功保存并应用！',

    // 通用按钮与状态
    btn_save: '保存个性设置',
    btn_close: '关闭窗口',
    btn_open_chat: '打开即时聊天',
    btn_copy_link: '复制链接',
    btn_pause_shift: '暂停当班',
    btn_resume_shift: '恢复接单',
    status_on_duty: '值班中',
    status_paused: '暂停中',
    status_connected: '在线连接',
    search_placeholder: '全局搜索订单、商品或功能...',
    logout: '安全退出登录',
    verify_phone: '验证手机号',
    change_branch: '切换当前分店',
    no_branches: '暂无可用分店',

    // 移动Dock与徽章
    tab_summary: '总览',
    tab_products: '商品',
    tab_chat: '群聊',
    tab_owners: '店长',
    tab_delivery: '配送',
    tab_menu: '菜单',
    tab_station: '工作台',
    tab_store: '商城',
    tab_employees: '员工',
    back_to_store: '返回商城首页',
    view_public_store: '浏览前台商城',
    collapse_sidebar: '折叠侧边栏',
    expand_sidebar: '展开侧边栏',
    superadmin: '超级管理员',
    role_owner: '店长 / 老板',
    role_employee: '营业员 / 员工',
    role_programmer: '开发技术员',
    badge_live: '实时在线',
    badge_inventory: '库存仓库',
    badge_catalog: '前台目录',
    badge_management: '管理调度',
    badge_shipping: '物流发货',

    // 员工工作台
    dash_active_station: '当前工作台',
    dash_branch_main: '总部分店',
    dash_welcome: '欢迎回来',
    dash_employee_subtitle: '已为您加载匹配岗位职责的操作看板：',
    dash_shift_status: '当班考勤状态',
    dash_on_duty_label: '正常服务中',
    dash_on_pause_label: '暂离休息中',
    dash_tab_orders_qr: '订单处理与核销码',
    dash_tab_station_tools: '岗位工具与协同',
    dash_tab_referral: '我的推广分销码',
    dash_collaborative_title: '录入与维护商城商品',
    dash_collaborative_desc: '协同添加新商品、上调促销价格、更新规格与分类。亦可提交特惠折扣由店长或开发审批。',
    dash_manage_products_btn: '进入商品管理',
    dash_internal_chat_title: '员工团队即时群聊',
    dash_internal_chat_desc: '与当班同事即时沟通交接班、协调收银、紧急库存调拨或报备异常情况。',
    dash_open_chat_btn: '进入工作群聊',
    dash_cashier_opening: '收银初始备用金',
    dash_cashier_opening_note: '底金核验无误',
    dash_cashier_sales_today: '今日收款总计',
    dash_cashier_sales_waiting: '等待首笔收银交易',
    dash_cashier_tickets: '已开出发票小票',
    dash_cashier_tickets_note: '当前班次单数',
    dash_warehouse_received: '入库商品总数',
    dash_warehouse_received_note: '最近7天入库',
    dash_warehouse_low_stock: '库存不足报警',
    dash_warehouse_low_stock_note: '建议及时补货',
    dash_warehouse_transfers: '分店调拨记录',
    dash_warehouse_transfers_note: '在途调拨处理',
    dash_general_active_tasks: '待办协同事项',
    dash_general_tasks_assigned: '今日指派',
    dash_general_urgent_alerts: '紧急事项提醒',
    dash_general_all_clear: '运转正常无警报',
    dash_general_branch: '所属值班门店',

    // 核销二维码面板
    qr_panel_title: '外送员专用核销二维码',
    qr_panel_desc: '外送员到达 {branch} 柜台后扫描此二维码，即可核对订单明细并登记收款完成交接。',
    qr_type_dynamic: '动态码 (2分钟有效)',
    qr_type_fixed: '固定码 (前台立牌)',
    qr_security_flow: '安全核销指引',
    qr_step_1: '外送员到达柜台，打开手机相机直接扫描此二维码。',
    qr_step_2: '输入配送员姓名并选择所属外送公司（无需账号密码）。',
    qr_step_3: '在待出库列表中选中对应客户的订单。',
    qr_step_4: '核验商品无误后登记收款方式，完成货款交接。',
    qr_direct_link: '快捷核销网页链接',
    qr_btn_regenerate: '立即生成新二维码',
    qr_auto_refresh: '自动刷新倒计时：',
    qr_generating: '正在生成二维码...',
    qr_copied: '核销链接已成功复制！',

    // 订单实时监控面板
    orders_title: '实时订单监控',
    orders_inbox: '客户消息收件箱',
    orders_live: 'Firestore 实时同步中',
    orders_tab_all: '全部订单',
    orders_tab_pending: '待处理',
    orders_tab_preparing: '备货中',
    orders_tab_waiting: '等待客户确认',
    orders_tab_ready: '备好待核销',
    orders_tab_validated: '已核销完成',
    orders_empty_title: '此分类暂无订单',
    orders_empty_desc: '新客户下单后将即时呈现在此列表中。',
    orders_card_order: '订单编号',
    orders_card_customer: '顾客姓名',
    orders_card_total: '应收总额',
    orders_card_items: '件商品',
    orders_btn_prepare: '开始备货打包',
    orders_btn_missing: '缺货沟通报备',
    orders_btn_ready: '备好可供取货',
    orders_btn_chat: '联系客户沟通',

    // 店长管理后台
    owner_portal_badge: '店长/商户管理后台',
    owner_active_branches: '家营业分店',
    owner_dashboard_title: '门店全局管控中心',
    owner_dashboard_desc: '统筹管理各分店运营、员工团队考勤与全渠道订单实时流转。',
    owner_btn_new_branch: '新建分店',
    owner_btn_products: '商品与折扣审核',
    owner_btn_employees: '员工团队管理',
    owner_tab_orders: '订单与配送监控',
    owner_tab_qr: '分店核销码配置',
    owner_tab_branches: '分店列表与营业信息',
    owner_tab_metrics: '销售业绩与统计报表',
    owner_stat_sales_today: '今日营业额',
    owner_stat_pending_orders: '待处理订单',
    owner_stat_active_products: '在售商品数',
    owner_stat_active_staff: '在岗员工数',

    // 开发者后台
    prog_console_badge: '系统开发者全局主控台',
    prog_superadmin: '超级管理员权限 (SUPERADMIN)',
    prog_title: '系统底层控制中枢',
    prog_desc: '全方位监控 Firebase Auth 认证体系、开发者团队、商户店长授权及员工全局档案。',
    prog_btn_add_prog: '+ 添加开发者',
    prog_btn_delivery: '外送物流公司',
    prog_btn_owners: '商户店长管理',
    prog_tab_overview: '全局综合概览',
    prog_tab_programmers: '技术研发团队',
    prog_tab_owners: '店长与负责人',
    prog_tab_delivery: '合作配送物流',
    prog_tab_employees: '员工全局花名册',
    prog_tab_audit: '系统安全审计日志',
    prog_tab_database: 'RTDB 实时数据库',

    // 岗位区域
    area_caja: '收银结账',
    area_bodega: '仓储库存',
    area_empaque: '打包发货',
    area_cocina: '备餐后厨',
    area_despacho: '物流调度',
    area_general: '综合服务',

    // 推广分销
    ref_title: '我的推广分销专属链接',
    ref_desc: '分享您的专属二维码或推广链接，客户成单后将自动计入您的业绩提成。',

    // 商品与库存
    prod_module_badge: '统一库存管理模块',
    prod_management_title: '商品与折扣管理',
    prod_management_desc: '店长和员工均可上传商品、价格、描述与分类。员工申请的特惠折扣需经店长或开发者审批通过后方可在前台展示。',
    prod_btn_new_category: '新建分类',
    prod_btn_add_product: '添加商品',
    prod_pending_discounts_title: '待审核特惠折扣申请',
    prod_can_authorize: '您拥有审核并批准或驳回折扣的权限',
    prod_waiting_review: '等待店长或开发者审核中',
    prod_discount_reason: '申请原因',
    prod_proposed_by: '申请人',
    prod_btn_approve: '批准折扣',
    prod_btn_reject: '驳回',
    prod_pending_badge: '待审核',
    prod_search_placeholder: '按商品名称、分类或描述搜索...',
    prod_filter_all_cats: '全部分类',
    prod_filter_all_status: '全部状态',
    prod_filter_discounted: '活动折扣中',
    prod_filter_pending: '待审核折扣',
    prod_empty_title: '当前视图暂无商品',
    prod_empty_desc: '您可以使用上方按钮添加新商品，录入价格、描述与所属分类。',
    prod_btn_add_first: '添加首件商品',
    prod_card_edit: '编辑',
    prod_card_discount: '申请折扣',
    prod_card_barcode: '商品条形码',
    prod_card_in_stock: '现货库存',
    prod_card_low_stock: '库存紧张',
    prod_card_out_of_stock: '已售罄',
    prod_cat_tools: '五金工具',
    prod_cat_shoes: '男女鞋靴',
    prod_cat_clothing: '流行服饰',
    prod_cat_lingerie: '内衣塑身',
    prod_cat_cosmetics: '美妆护肤',
    prod_cat_electronics: '数码潮玩',
    prod_cat_snacks: '特色零食',
    prod_cat_caps: '帽子配饰',
    prod_cat_home: '家居厨具',
    prod_cat_seasonal: '时令节庆',
    prod_cat_adult: '成人用品',
    prod_cat_general: '综合商品',

    // 员工即时群聊
    chat_title: '员工内部即时群聊',
    chat_desc: '与同分店同事即时交流、快捷查询库存、协调交接班事宜。',
    chat_search_placeholder: '搜索频道或同事姓名...',
    chat_team_rooms: '团队频道',
    chat_coworkers: '当班同事',
    chat_no_coworkers: '暂未找到同班同事。',
    chat_on_shift: '当班中',
    chat_active_channel: '当前活跃频道',
    chat_syncing: '正在同步频道最新消息...',
    chat_empty_title: '此频道暂无历史消息',
    chat_empty_desc: '快来发送第一条消息吧！可随时咨询库存、协调交接班或发布工作通知。',
    chat_urgent_badge: '紧急工作通报',
    chat_shift_badge: '交接班记录',
    chat_stock_badge: '库存调拨咨询',
    chat_quick_tags: '快捷标签:',
    chat_tag_urgent: '紧急',
    chat_tag_shift: '交接班',
    chat_tag_stock: '查库存',
    chat_placeholder_urgent: '输入高优先级或紧急通知内容...',
    chat_placeholder_shift: '记录上岗打卡、交接班或休息报备...',
    chat_placeholder_stock: '查询或通知某件商品的实际库存...',
    chat_placeholder_general: '发消息给',
    chat_btn_send: '发送',
    chat_ch_general: '📢 团队全员大厅',
    chat_ch_general_desc: '全店通报与日常公告',
    chat_ch_ferreteria: '🔧 五金与前台',
    chat_ch_ferreteria_desc: '工具规格、售价及现场库存问询',
    chat_ch_caja: '💳 收银与开票',
    chat_ch_caja_desc: '交接班对账、小票开具及支付确认',
    chat_ch_bodega: '📦 仓储与配货',
    chat_ch_bodega_desc: '进销存点货、到货签收与出库配齐',

    // 店长后台补充
    owner_onboarding_required: '需要完成初始化设置',
    owner_onboarding_welcome: '欢迎使用 Sayta Mall',
    owner_onboarding_desc: '为了开始接单并录入员工账号，请先创建您的第一家营业分店。',
    owner_stat_active_branch: '当前营业分店',
    owner_stat_online: '正常营业中',
    owner_stat_currency: '结算币种',
    owner_stat_currency_local: '当地标准货币',
    owner_stat_dispatch: '提发货方式',
    owner_stat_enabled: '已启用',
    owner_stat_staff: '在岗人员',
    owner_stat_active: '正常在岗',
    owner_stat_manager_avail: '管理系统就绪',
    owner_card_employees_title: '员工与排班管理',
    owner_card_employees_desc: '录入员工账号与密码，分配所属分店及岗位职责（收银、仓储、前台、保洁、客服或综合岗）。',
    owner_card_employees_btn: '打开员工与岗位管理',
    owner_card_products_title: '商品目录与折扣审核',
    owner_card_products_desc: '查看员工录入的商品目录，快速审核各分店提交的促销特惠与打折申请。',
    owner_card_products_btn: '管理商品与折扣',
    owner_registered_branches: '已登记',
    owner_referral_program: '我的推广分销计划',
    owner_single_branch_active: '家营业分店',
    owner_multi_branch_active: '家营业分店',

    // 开发者后台补充
    prog_tab_staff: '员工与人事档案',
    prog_tab_system: '系统运行状态',
    prog_tab_logs: '系统审计日志',
    prog_tab_audit_staff: '员工操作审计',
    prog_tab_users: '全站注册用户',
    prog_tab_referral: '开发者推广链接',
    prog_tab_cronjobs: '定时任务调度',
    prog_tab_qr_branch: '分店核销二维码',

    // 缺货报备弹窗
    missing_modal_title: '报备缺货 / 不可用商品',
    missing_modal_desc: '标记商品不可用后，订单将变更为“等待客户确认”状态并暂缓配送。系统将为客户开启即时沟通通道以供确认。',
    missing_btn_notify: '暂停订单并通知客户',
    missing_btn_add_another: '添加另一件缺货商品',
    missing_opt_out_of_stock: '分店已售罄',
    missing_opt_damaged: '商品瑕疵或临期损坏',
    missing_opt_inventory_diff: '盘点库存账实不符',
    missing_suggest_title: '推荐替换备选商品 (可选)',
    missing_substitute_name: '替换商品名称',
    missing_substitute_price: '建议售价',

    // 外送配送公司页面
    delivery_badge: '物流 & 同城配送管理',
    delivery_live_badge: '实时在线',
    delivery_title: '外送 / 物流配送公司',
    delivery_desc: '注册并管理本地同城配送公司。顾客可在结算页面选择配送公司，订单将直接发送至其 WhatsApp 或通过网页系统转接。',
    delivery_btn_register: '注册新配送公司',
    delivery_stat_total: '配送公司总数',
    delivery_stat_total_sub: '已在系统注册',
    delivery_stat_active: '结算页面激活中',
    delivery_stat_active_sub: '顾客可见可选',
    delivery_stat_zones: '覆盖配送区域',
    delivery_stat_zones_sub: '已激活配送范围',
    delivery_stat_orders: '已转接订单',
    delivery_stat_orders_sub: '经网页或 WhatsApp',
    delivery_search_placeholder: '按公司名称、WhatsApp 或区域搜索...',
    delivery_filter_all: '全部',
    delivery_filter_active: '激活中',
    delivery_filter_inactive: '已停用',
    delivery_loading: '正在加载配送公司信息...',
    delivery_empty_title: '未找到配送公司',
    delivery_empty_search: '没有符合搜索条件的配送公司，请换个词重试。',
    delivery_empty_first: '注册您的第一家配送公司，让顾客在结算时可以选择。',
    delivery_btn_register_now: '立即注册配送公司',
    delivery_active_label: '结算页可选中',
    delivery_inactive_label: '已停用（隐藏）',
    delivery_rate_label: '配送费用',
    delivery_rate_value: '按目的地定价',
    delivery_zones_label: '覆盖区域',
    delivery_orders_label: '转接订单',
    delivery_btn_test: '测试 WhatsApp',
    delivery_btn_edit: '编辑',
    delivery_btn_toggle_active: '激活公司',
    delivery_btn_toggle_inactive: '停用公司',
    delivery_btn_delete: '删除公司',
    delivery_modal_create_title: '注册新配送公司',
    delivery_modal_edit_title: '编辑配送公司信息',
    delivery_form_name: '公司名称 *',
    delivery_form_name_placeholder: '例如：摩托快递 Chichigalpa',
    delivery_form_whatsapp: '国际 WhatsApp 号码 *',
    delivery_form_phone: '固定电话（选填）',
    delivery_form_email: '电子邮箱（选填）',
    delivery_form_zones: '覆盖区域（逗号分隔）*',
    delivery_form_zones_placeholder: '例如：市中心、San Antonio 社区、El Carmen 街区',
    delivery_form_logo: 'Logo 图片链接（选填）',
    delivery_form_status: '状态：结算页面激活显示',
    delivery_btn_cancel: '取消',
    delivery_btn_save: '保存修改',
    delivery_btn_create: '注册配送公司',
    delivery_btn_submitting: '提交中...',
    delivery_delete_title: '删除配送公司',
    delivery_delete_desc: '您确定要删除',
    delivery_delete_warning: '如有关联订单，此操作可能将其停用。',
    delivery_btn_delete_confirm: '确认删除',
    delivery_btn_deleting: '删除中...',

    // 店长管理页面
    owners_badge: '超级管理员控制台',
    owners_count_label: '家已注册店长',
    owners_title: '商户店长管理',
    owners_desc: '管理加盟商与店长的系统访问权限。可通过邮件发送邀请、临时封禁账号、开启客服协助模式，或进行二次确认后删除账号。',
    owners_btn_add: '添加店长',
    owners_search_placeholder: '按姓名、邮箱或店铺名称搜索...',
    owners_col_owner: '店长 & 邮箱',
    owners_col_store: '所属店铺',
    owners_col_branches: '分店数',
    owners_col_status: '状态',
    owners_col_date: '注册日期',
    owners_col_actions: '操作',
    owners_status_active: '正常',
    owners_status_suspended: '已封禁',
    owners_status_pending: '7天待激活',
    owners_invite_pending: '邀请待确认',
    owners_branches_label: '家分店',
    owners_branches_plural: '家分店',
    owners_btn_view: '查看店长后台',
    owners_btn_support: '客服协助模式',
    owners_btn_suspend: '封禁账号',
    owners_btn_restore: '恢复账号',
    owners_btn_delete: '删除店长',
    owners_empty_title: '暂未注册任何店长',
    owners_empty_desc: '添加第一位加盟店长的邮箱账号与密码以开始管理。',
    owners_modal_title: '注册新商户店长',
    owners_modal_desc: '创建店长的登录凭证。系统将自动发送欢迎邮件及登录引导。',
    owners_form_name: '店长姓名 *',
    owners_form_name_ph: '例如：薛霞',
    owners_form_email: '电子邮箱 *',
    owners_form_email_ph: 'laoban@example.com',
    owners_form_store: '店铺名称 *',
    owners_form_store_ph: '例如：Sayta Mall Chichigalpa',
    owners_form_password: '临时密码 *',
    owners_form_password_ph: '至少 6 个字符',
    owners_form_branch: '分配分店',
    owners_btn_create: '注册店长',
    owners_btn_creating: '注册中...',
    owners_delete_title: '删除商户店长',
    owners_delete_desc: '此操作不可逆。请输入店铺的精确名称以确认删除：',
    owners_delete_type_label: '输入精确名称：',
    owners_delete_type_ph: '店铺精确名称',
    owners_btn_delete_confirm: '永久删除',
    owners_btn_deleting: '删除中...',

    // 分类管理器
    cat_manager_badge: '商品分类体系',
    cat_manager_title: '商品分类管理',
    cat_manager_desc: '创建自定义分类以整理您的商品。系统预设分类为只读，不可修改。',
    cat_manager_my_title: '我的自定义分类',
    cat_manager_custom_badge: '个自定义',
    cat_manager_system_title: '系统预设分类',
    cat_manager_readonly_badge: '只读',
    cat_manager_new_btn: '新建分类',
    cat_manager_form_title: '新建自定义商品分类',
    cat_manager_form_name: '分类名称 *',
    cat_manager_form_name_ph: '例如：夏季特惠',
    cat_manager_form_icon: '图标（Emoji）',
    cat_manager_form_desc: '简要描述（选填）',
    cat_manager_form_desc_ph: '例如：旺季热销商品',
    cat_manager_form_badge: '标签（选填）',
    cat_manager_form_badge_ph: '例如：新品、促销、爆款',
    cat_manager_form_cancel: '取消',
    cat_manager_form_save: '保存分类',
    cat_manager_form_saving: '保存中...',
    cat_manager_empty_title: '您尚未创建任何自定义分类。',
    cat_manager_empty_btn: '创建第一个分类 →',
    cat_manager_edit_save: '保存',
    cat_manager_edit_cancel: '取消',
    cat_manager_delete_confirm: '删除',
    cat_manager_delete_cancel: '取消',
    cat_manager_loading: '正在加载分类...',

    // 开发者控制台概览面板
    prog_stat_owners: '已注册店长数',
    prog_stat_owners_link: '查看完整目录 ›',
    prog_stat_branches: '当前营业分店',
    prog_stat_branches_sub: '正常运营中',
    prog_stat_users: '全站注册用户',
    prog_stat_users_link: '查看用户表与凭证 ›',
    prog_stat_firebase: 'Firebase Admin SDK',
    prog_stat_firebase_status: '已连接',
    prog_stat_roles: '角色权限安全',
    prog_stat_roles_status: '已激活',
    prog_card_prog_title: '技术研发团队',
    prog_card_prog_sub: '开发者账号创建与管理',
    prog_card_prog_desc: '创建并管理开发者账号，分配专属密码与角色权限，协同参与平台运营管理。',
    prog_card_prog_btn: '管理开发者账号',
    prog_card_owners_title: '商户店长目录',
    prog_card_owners_sub: '加盟商与门店全局管控',
    prog_card_owners_desc: '生成7天有效期专属邀请令牌、开启店长视角协助模式，或全程审计留痕地撤销店长访问权限。',
    prog_card_owners_btn: '前往店长管理',
    prog_card_emp_title: '员工全局花名册',
    prog_card_emp_sub: '直接创建账号并分配岗位',
    prog_card_emp_desc: '创建员工操作账号，分配标准或自定义岗位工作区域，提升管理精细化水平。',
    prog_card_emp_btn: '打开员工管理模块',
    prog_card_users_title: '全站注册用户中央目录',
    prog_card_users_badge: '开发者专属',
    prog_card_users_sub: '包含姓名、邮箱、年龄、地址、密码及按月年修改记录的完整用户档案表。',
    prog_card_users_btn: '查看用户档案表',
    prog_card_users_feat1_title: '数据表格视图',
    prog_card_users_feat1_sub: '响应式布局，列结构清晰有序',
    prog_card_users_feat2_title: '按月/年筛选',
    prog_card_users_feat2_sub: '按注册日期或时间段查询用户',
    prog_card_users_feat3_title: '密码与变更记录',
    prog_card_users_feat3_sub: '查看原始密码或最后修改时间',
    prog_card_users_feat4_title: '地址与年龄',
    prog_card_users_feat4_sub: '全量用户个人资料与收件信息',
    prog_system_title: '系统架构 & 实时服务监控',
    prog_system_nextjs_status: '运行正常 (200 OK)',
    prog_system_firestore_status: '实时同步',
    prog_system_prices: '价格隐藏保护系统',
    prog_system_prices_sub: '未登录访客无法查看价格与购买按钮',
    prog_system_prices_status: '已保护',
    prog_system_currency: '系统结算货币',
    prog_system_currency_sub: '默认尼加拉瓜科多巴 (C$ / NIO)，使用 Intl 标准格式化',
    prog_system_currency_status: '已配置',
    prog_logs_title: '系统事件日志与安全审计',
    prog_referral_desc: '管理您作为开发者的专属推广分销链接。通过此链接产生的每笔销售均自动记录至您的账户业绩。',
    prog_emp_console_title: '超级管理员控制台 · 员工花名册',
    prog_emp_console_sub: '为任意分店创建员工账号与密码，并管理您的自定义岗位工作区域。',
    prog_system_firestore: 'Firestore 实时数据库',
    dash_station_tools: '收银工作台操作',
    dash_sale_direct: '创建现场直售订单',
    dash_sale_direct_desc: '浏览在售商品并收款结账',
    dash_validate_delivery: '核验外送骑手取货',
    dash_validate_delivery_desc: '生成外送核验动态二维码',
    dash_cash_partial: '当班收银阶段对账',
    dash_cash_partial_desc: '清点并上报当前抽屉现金',
    dash_shift_history: '交接班流水记录',
    dash_shift_history_desc: '查看本班次历史结账流水',
    dash_warehouse_scan_desc: '条形码扫码入库与盘点',
    orders_status_on_way: '配送中',
    orders_status_delivered: '已送达',
    orders_status_cancelled: '已取消',
    orders_hide_items: '收起商品拣货清单',
    orders_show_items: '展开待备货商品清单',
    orders_loading_items: '正在加载商品清单...',
    orders_ready_msg: '备货就绪，等待骑手在前台扫码核验...',
    orders_btn_dispatch: '确认发货（配送中）',
    orders_btn_deliver: '确认交付给客户',
    orders_btn_cancel: '取消订单并返还库存',
    emp_mgr_title: '员工团队与岗位工作区域管理',
    emp_mgr_sub: '为员工分配安全登录凭证、绑定所在分店，并细化工作区域（收银、仓储、销售等）。',
    emp_mgr_btn_add: '新建员工',
    emp_mgr_btn_areas: '管理工作区域',
    emp_mgr_search_ph: '按姓名、邮箱或电话搜索员工...',
    emp_mgr_filter_area: '全部工作区域',
    emp_mgr_filter_branch: '全部分店',
    emp_mgr_stat_total: '员工总数',
    emp_mgr_stat_active: '在岗当值',
    emp_mgr_stat_paused: '暂停休班',
    emp_mgr_th_employee: '员工信息',
    emp_mgr_th_area: '工作区域 / 岗位',
    emp_mgr_th_branch: '所属分店',
    emp_mgr_th_credentials: '登录凭证',
    emp_mgr_th_status: '状态',
    emp_mgr_th_actions: '操作',
    emp_mgr_badge_custom: '自定义岗位',
    emp_mgr_btn_toggle_active: '恢复当班',
    emp_mgr_btn_toggle_pause: '暂停当班',
    emp_mgr_btn_delete: '删除员工账号',
    emp_mgr_copied_pass: '密码已成功复制！',
    emp_mgr_empty_title: '暂无登记的员工',
    emp_mgr_empty_desc: '请点击右上角按钮为分店添加第一名工作人员。',
    emp_mgr_empty_btn: '创建首个员工',
    emp_mgr_modal_new_title: '登记新员工账号',
    emp_mgr_modal_new_desc: '设置员工账号密码，并指定分店与工作岗位。',
    emp_mgr_form_name: '员工全名 *',
    emp_mgr_form_name_ph: '例如：李明',
    emp_mgr_form_email: '登录邮箱 *',
    emp_mgr_form_email_ph: 'employee@saytamall.com',
    emp_mgr_form_pass: '登录密码 *',
    emp_mgr_form_pass_ph: '至少6位字符',
    emp_mgr_form_pass_gen: '生成安全密码',
    emp_mgr_form_phone: '联系电话 / WhatsApp',
    emp_mgr_form_phone_ph: '例如：+505 8888 8888',
    emp_mgr_form_branch: '所属分店 *',
    emp_mgr_form_area: '工作岗位区域 *',
    emp_mgr_form_cancel: '取消',
    emp_mgr_form_save: '确认登记员工',
    emp_mgr_form_saving: '登记中...',
    emp_mgr_delete_title: '确认删除员工',
    emp_mgr_delete_desc: '您确定要注销此员工账号吗？该操作不可撤销。',
    emp_mgr_delete_confirm: '确认永久删除',
    emp_mgr_delete_canceling: '正在删除...',
    prog_mgr_title: '核心研发工程师团队',
    prog_mgr_sub: '管理拥有开发者控制台、技术API和全站数据库操作特权的核心技术人员。',
    prog_mgr_btn_add: '新建开发者',
    prog_mgr_search_ph: '按姓名或技术邮箱搜索开发者...',
    prog_mgr_th_programmer: '开发者信息',
    prog_mgr_th_role: '技术岗位',
    prog_mgr_th_date: '入驻日期',
    prog_mgr_th_access: '特权级别',
    prog_mgr_th_actions: '操作',
    prog_mgr_badge_root: '最高超级管理员 Root',
    prog_mgr_badge_standard: '后端 / 前端核心工程师',
    prog_mgr_empty_title: '暂无其他开发者',
    prog_mgr_empty_desc: '可为团队成员创建开发者账号协同开发与运维。',
    prog_mgr_modal_title: '创建新开发者账号',
    prog_mgr_modal_desc: '分配专属高权限开发者凭证，协同管理系统。',
    prog_mgr_form_role: '技术职位 / 专业领域',
    prog_mgr_form_role_ph: '例如：全栈工程师',
    prog_mgr_form_save: '创建开发者',
    prog_mgr_form_saving: '创建中...',
    audit_mgr_title: '商品与价格安全审计日志',
    audit_mgr_sub: '实时记录全站商品价格修改、自动折扣应用与库存增删记录。',
    audit_mgr_search_ph: '输入商品名称、SKU或操作员筛选...',
    audit_mgr_filter_all: '全量操作类型',
    audit_mgr_th_action: '操作类型',
    audit_mgr_th_details: '涉及商品 / 详情',
    audit_mgr_th_change: '价格变更幅度',
    audit_mgr_th_user: '操作账号',
    audit_mgr_th_date: '操作时间',
    audit_mgr_empty: '根据当前筛选条件未找到相关审计日志。',
    branch_mgr_title: '实体分店与营业网点管理',
    branch_mgr_sub: '集中配置各分店地址、营业时间、联系方式及外送履约规则。',
    branch_mgr_btn_edit: '编辑分店',
    branch_mgr_btn_delete: '删除分店',
    branch_mgr_btn_save: '保存分店信息',
    branch_mgr_btn_saving: '保存中...',
    branch_mgr_field_name: '分店名称',
    branch_mgr_field_address: '详细街道地址',
    branch_mgr_field_city: '所属城市 / 区域',
    branch_mgr_field_phone: '主联系电话',
    branch_mgr_field_whatsapp: '官方 WhatsApp',
    branch_mgr_field_schedule: '营业时间表',
    branch_mgr_field_currency: '收银结算币种',
    branch_mgr_field_delivery: '履约发货方式',
    branch_mgr_delivery_both: '支持到店自提与同城配送',
    branch_mgr_delivery_pickup: '仅支持到店自提',
    branch_mgr_delivery_ship: '仅支持同城配送',
    branch_mgr_empty_title: '暂无已配置分店',
    branch_mgr_empty_desc: '请先创建首家实体分店以激活全站销售与排班功能。',
    users_reg_title: '全站注册用户中央总名册',
    users_reg_sub: '聚合全站客户、员工、店长和技术开发者的统一用户数据库。',
    users_reg_search_ph: '按姓名、邮箱或手机号搜索用户...',
    users_reg_filter_role: '全部角色类型',
    users_reg_filter_month: '按注册月份',
    users_reg_filter_year: '按注册年份',
    users_reg_th_user: '用户名称',
    users_reg_th_role: '系统角色',
    users_reg_th_contact: '联系方式',
    users_reg_th_location: '配送地址与年龄',
    users_reg_th_credentials: '初始凭证与修改记录',
    users_reg_th_date: '注册时间',
    users_reg_th_actions: '操作',
    users_reg_btn_refresh: '刷新数据',
    users_reg_btn_export: '导出 CSV',
    users_reg_empty: '未检索到符合条件的用户档案。',
    users_reg_copied_pass: '用户密码已复制到剪贴板',
    branch_qr_title: '分店外送取货二维码管理中心',
    branch_qr_sub: '生成与管理前台动态二维码，供外送骑手扫码核验并确认出餐。',
    branch_qr_btn_rotate: '立即刷新安全密钥',
    branch_qr_btn_download: '下载高清二维码',
    branch_qr_btn_print: '打印立牌告示',
    branch_qr_btn_fullscreen: '全屏核验展示',
    branch_qr_mode_dynamic: '动态刷新码（高安全性）',
    branch_qr_mode_fixed: '柜台固定展示码',
    branch_qr_expiry_label: '密钥有效倒计时',
    branch_qr_history_title: '近期骑手扫码核验记录',
    branch_qr_history_empty: '当前二维码暂无扫码核验记录。',
    ref_panel_title: '渠道推广与销售分成计划',
    ref_panel_sub: '分享您的专属推广链接，由该链接产生的所有订单都将计入您的业绩。',
    ref_panel_copy_btn: '复制推广链接',
    ref_panel_copied: '链接已复制！',
    ref_panel_link_label: '您的专属销售推广链接',
    ref_panel_total_sales: '累计推广销售额',
    ref_panel_commissions: '累计产生佣金',
    ref_panel_note: '任何顾客通过您的链接下单，系统将全自动将业绩归属于您的账号。',

  },
};

interface DashboardPreferencesContextValue {
  theme: DashboardTheme;
  language: DashboardLanguage;
  setTheme: (theme: DashboardTheme) => void;
  setLanguage: (lang: DashboardLanguage) => void;
  t: (key: string, fallback?: string) => string;
  themeConfig: ThemeConfig;
  settingsModalOpen: boolean;
  setSettingsModalOpen: (open: boolean) => void;
  isZh: boolean;
  isEn: boolean;
  isEs: boolean;
}

const DashboardPreferencesContext = createContext<DashboardPreferencesContextValue | null>(null);

export function DashboardPreferencesProvider({ children }: { children: ReactNode }) {
  const { user, claims } = useAuth();
  const userId = user?.uid || 'default_user';

  const storageThemeKey = `sayta_theme_${userId}`;
  const storageLangKey = `sayta_lang_${userId}`;

  const [theme, setThemeState] = useState<DashboardTheme>('obsidian');
  const [language, setLanguageState] = useState<DashboardLanguage>('es');
  const [settingsModalOpen, setSettingsModalOpen] = useState(false);

  useEffect(() => {
    try {
      const savedTheme = localStorage.getItem(storageThemeKey) as DashboardTheme;
      const globalTheme = localStorage.getItem('sayta_theme');
      if (savedTheme && DASHBOARD_THEMES[savedTheme]) {
        setThemeState(savedTheme);
      } else if (globalTheme === 'light') {
        // Si no tiene preferencia guardada pero la app está en modo claro, adoptar tema light
        setThemeState('light');
      }

      const savedLang = (localStorage.getItem(storageLangKey) || localStorage.getItem('sayta_global_lang') || localStorage.getItem('sayta_dashboard_lang')) as DashboardLanguage;
      if (savedLang && TRANSLATIONS[savedLang]) {
        setLanguageState(savedLang);
        if (typeof document !== 'undefined') {
          document.documentElement.lang = savedLang === 'zh' ? 'zh-CN' : savedLang;
        }
      }
    } catch {}
  }, [storageThemeKey, storageLangKey]);

  useEffect(() => {
    const handleGlobalLangChange = (e: any) => {
      const newLang = e?.detail as DashboardLanguage;
      if (newLang && TRANSLATIONS[newLang] && newLang !== language) {
        setLanguageState(newLang);
      }
    };
    window.addEventListener('sayta_lang_change', handleGlobalLangChange);
    return () => window.removeEventListener('sayta_lang_change', handleGlobalLangChange);
  }, [language]);

  const setTheme = useCallback((newTheme: DashboardTheme) => {
    setThemeState(newTheme);
    try {
      localStorage.setItem(storageThemeKey, newTheme);
      if (typeof document !== 'undefined') {
        if (newTheme === 'light') {
          localStorage.setItem('sayta_theme', 'light');
          document.documentElement.classList.remove('dark');
          document.documentElement.classList.add('light');
          document.documentElement.setAttribute('data-theme', 'light');
        } else {
          localStorage.setItem('sayta_theme', 'dark');
          document.documentElement.classList.remove('light');
          document.documentElement.classList.add('dark');
          document.documentElement.setAttribute('data-theme', 'dark');
        }
      }
    } catch {}
  }, [storageThemeKey]);

  const setLanguage = useCallback((newLang: DashboardLanguage) => {
    setLanguageState(newLang);
    try {
      localStorage.setItem(storageLangKey, newLang);
      localStorage.setItem('sayta_global_lang', newLang);
      localStorage.setItem('sayta_dashboard_lang', newLang);
      if (typeof document !== 'undefined') {
        document.documentElement.lang = newLang === 'zh' ? 'zh-CN' : newLang;
      }
      window.dispatchEvent(new CustomEvent('sayta_lang_change', { detail: newLang }));
    } catch {}
  }, [storageLangKey]);

  const t = useCallback((key: string, fallback?: string): string => {
    const langDict = TRANSLATIONS[language] || TRANSLATIONS.es;
    return langDict[key] || fallback || key;
  }, [language]);

  const themeConfig = DASHBOARD_THEMES[theme] || DASHBOARD_THEMES.obsidian;

  return (
    <DashboardPreferencesContext.Provider
      value={{
        theme,
        language,
        setTheme,
        setLanguage,
        t,
        themeConfig,
        settingsModalOpen,
        setSettingsModalOpen,
        isZh: language === 'zh',
        isEn: language === 'en',
        isEs: language === 'es',
      }}
    >
      {children}
    </DashboardPreferencesContext.Provider>
  );
}

export function useDashboardPreferences(): DashboardPreferencesContextValue {
  const context = useContext(DashboardPreferencesContext);
  if (!context) {
    return {
      theme: 'obsidian' as DashboardTheme,
      language: 'es' as DashboardLanguage,
      setTheme: () => {},
      setLanguage: () => {},
      t: (key: string, fallback?: string) => fallback || key,
      themeConfig: DASHBOARD_THEMES.obsidian,
      settingsModalOpen: false,
      setSettingsModalOpen: () => {},
      isZh: false,
      isEn: false,
      isEs: true,
    };
  }
  return context;
}
